### ISSUE TITLE
Qt-base 5.5.1-cvpixelbuffer-2.7z damaged

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#642] opened 2017-01-12 14:38 UTC
I'm trying to wrap my head around the Qt hunter package. For starters I tried to compile the example at `hunter/examples/qt-core`.

The file `hunter-5.5.1-cvpixelbuffer-2.7z` seems to be broken for me.

System:
- Ubuntu 16.04
- cmake version 3.5.1
- gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

```
$ cmake -H. -B_build
...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hunter/_Base/xxxxxxx/bb40d0d/e1266bb/Build/Qt/__qtbase/Build
Scanning dependencies of target Qt-qtbase
[ 12%] Creating directories for 'Qt-qtbase'
[ 25%] Performing download step (download, verify and extract) for 'Qt-qtbase'
-- verifying file...
     file='/home/hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z'
-- verifying file... done
-- extracting...
     src='/home/hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z'
     dst='/home/hunter/_Base/xxxxxxx/bb40d0d/e1266bb/QtBuild/10'
-- extracting... [tar xfz]
CMake Error: Problem with archive_read_next_header(): Damaged 7-Zip archive
CMake Error: Problem extracting tar: /home/hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z
-- extracting... [error clean up]
CMake Error at /home/hunter/_Base/xxxxxxx/bb40d0d/e1266bb/Build/Qt/__qtbase/Build/Qt-qtbase-prefix/src/Qt-qtbase-stamp/extract-Qt-qtbase.cmake:33 (message):
  error: extract of
  '/home//hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z'
  failed
```

**Comment by headupinclouds** [comment] 2017-01-12 16:13
I can help with a working example, but may not get to it until the weekend.

**Comment by NeroBurner** [comment] 2017-01-12 21:08
If we get the 5.7 version working I'd be most happy. Current upstream version is for me much more important than an old version

**Comment by headupinclouds** [comment] 2017-01-13 14:01
The file itself seems to be okay for me. This test is using OS X 10.12 w/ CMake 3.7.1.  Which CMake version are you using?

```
cmake --version
```
cmake version 3.7.1

```
cd /tmp/
git clone https://github.com/forexample/qt-resources-istream
cd qt-resources-istream/
polly --toolchain xcode
```

```
...
-- verifying file...
       file='/home/hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z'
-- File already exists and hash match (skip download):
  file='/home/hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z'
  SHA1='da8682218c7ed731d1affbdd1abee3c7393fb3e7'
cd /home/hunter/_Base/xxxxxxx/0156b82/b1691f6/QtBuild && /usr/local/Cellar/cmake/3.7.1/bin/cmake -P /home/hunter/_Base/xxxxxxx/0156b82/b1691f6/Build/Qt/__qtbase/Build/Qt-qtbase-prefix/src/Qt-qtbase-stamp/verify-Qt-qtbase.cmake
cd /home/hunter/_Base/xxxxxxx/0156b82/b1691f6/QtBuild && /usr/local/Cellar/cmake/3.7.1/bin/cmake -P /home/hunter/_Base/xxxxxxx/0156b82/b1691f6/Build/Qt/__qtbase/Build/Qt-qtbase-prefix/src/Qt-qtbase-stamp/extract-Qt-qtbase.cmake
-- extracting...
     src='/home/hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z'
     dst='/home/hunter/_Base/xxxxxxx/0156b82/b1691f6/QtBuild/10'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
```

**Comment by NeroBurner** [comment] 2017-01-13 14:55
cmake version 3.5.1 (Ubuntu 16.04 default)

finishes without problem
```
git clone https://github.com/forexample/qt-resources-istream
cd qt-resources-istream/
cmake -H. -B_build
```

v0.14.29 is rather old, updating to latest v0.17.12
```
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.17.12.tar.gz"
    SHA1 "74cfa490ef0d3ff8916523bbf5add53049aad7be"
)
```

error
```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/.hunter/_Base/74cfa49/0156b82/e1266bb/Build/Qt/__qtbase/Build
Scanning dependencies of target Qt-qtbase
[ 12%] Creating directories for 'Qt-qtbase'
[ 25%] Performing download step (download, verify and extract) for 'Qt-qtbase'
-- downloading...
     src='https://github.com/hunter-packages/Qt/releases/download/v5.5.1-cvpixelbuffer-2-p9/hunter-5.5.1-cvpixelbuffer-2.7z'
     dst='/home/.hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z'
     timeout='none'
-- [download 0% complete]

...

-- [download 100% complete]
-- downloading... done
-- verifying file...
     file='/home/.hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z'
-- verifying file... done
-- extracting...
     src='/home/.hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z'
     dst='/home/.hunter/_Base/74cfa49/0156b82/e1266bb/QtBuild/10'
-- extracting... [tar xfz]
CMake Error: Problem with archive_read_next_header(): Damaged 7-Zip archive
CMake Error: Problem extracting tar: /home/.hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z
-- extracting... [error clean up]
CMake Error at /home/.hunter/_Base/74cfa49/0156b82/e1266bb/Build/Qt/__qtbase/Build/Qt-qtbase-prefix/src/Qt-qtbase-stamp/extract-Qt-qtbase.cmake:33 (message):
  error: extract of
  '/home/hunter/_Base/Download/Qt/5.5.1-cvpixelbuffer-2-p9/da86822/hunter-5.5.1-cvpixelbuffer-2.7z'
  failed
```

**Comment by ruslo** [comment] 2017-01-15 06:44
> cmake version 3.5.1 (Ubuntu 16.04 default)

Sounds like a CMake issue, can you try to update it to the latest version? See `3.4.1` note:
* https://docs.hunter.sh/en/latest/quick-start/cmake.html
* https://github.com/ruslo/hunter/issues/405

**Comment by ruslo** [comment] 2017-06-14 10:50
> Sounds like a CMake issue

Closing

**Closed by ruslo** 2017-06-14 10:50 UTC
Labels: discussion

**Comment by sjdrc** [comment] 2019-05-23 06:47
This is still occurring for me on arm64 platform. I'm using the latest hunter, and self compiled 3.14.3 cmake.

https://gist.github.com/sjdrc/7bcf128c34febebda6d8159ac4a38490

cmake has been built and linked against 3.1.2-11ubuntu0.16.04.6 of libarchive.

**Comment by ruslo** [comment] 2019-05-23 12:27
As already mentioned the problem is not about Hunter or created archive, problem is about CMake.

```
> cmake --version
cmake version 3.14.3

> wget https://github.com/hunter-packages/Qt/releases/download/v5.5.1-cvpixelbuffer-2-p9/hunter-5.5.1-cvpixelbuffer-2.7z
> cmake -E tar xf hunter-5.5.1-cvpixelbuffer-2.7z
> ls qtbase/configure
```

I see some warnings though:
```
...
cmake -E tar: warning: 7-Zip bad CRC: 0xa22a123f should be 0x714bb969
cmake -E tar: warning: 7-Zip bad CRC: 0xee976b70 should be 0xe8948f9d
cmake -E tar: warning: 7-Zip bad CRC: 0x20bd7c08 should be 0xd4f9238d
```

I see no issues while using `7z`:

```
> 7z x hunter-5.5.1-cvpixelbuffer-2.7z 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (206A7),ASM,AES-NI)

Scanning the drive for archives:
1 file, 310575326 bytes (297 MiB)

Extracting archive: hunter-5.5.1-cvpixelbuffer-2.7z
--
Path = hunter-5.5.1-cvpixelbuffer-2.7z
Type = 7z
Physical Size = 310575326
Headers Size = 1485824
Method = Delta LZMA:26 BCJ2
Solid = +
Blocks = 5

Everything is Ok                                                               

Folders: 14224
Files: 139089
Size:       1641734253
Compressed: 310575326
```
