### ISSUE TITLE
v0.15.30: GSL (https://github.com/ruslo/gsl/) 404

### ISSUE THREAD

**Issue by grisevg** [ruslo/hunter#527] opened 2016-09-23 14:44 UTC
Hunter fails to load GSL from a non-existent repo.

**Comment by headupinclouds** [comment] 2016-09-24 15:13
Can you provide more detail on this error, and a small sample that reproduces the issue?

**Comment by grisevg** [comment] 2016-09-24 15:36
Sorry, of course: 
I only added `hunter_add_package(GSL)` to `CMakeLists.txt` and then ran `cmake` and got the following error appearing over and over:
```
  -- downloading...
         src='https://github.com/ruslo/gsl/archive/v1.16.tar.gz'
         dst='C:/tools/hunter/_Base/Download/GSL/1.16/ce16e45/v1.16.tar.gz'
         timeout='none'
CUSTOMBUILD : error : downloading 'https://github.com/ruslo/gsl/archive/v1.16.tar.gz' failed [C:\tools\hunter\_Base\0a63c66\2e0e6b1\a812237\Build\GSL\Build\GSL-Release.vcxproj]
    status_code: 22
    status_string: "HTTP response code said error"
    log:
    --- LOG BEGIN ---
    timeout on name lookup is not supported
    Trying 192.30.253.112...
  Connected to github.com (192.30.253.112) port 443 (#0)
  schannel: SSL/TLS connection with github.com port 443 (step 1/3)
  schannel: disabled server certificate revocation checks
  schannel: sending initial handshake data: sending 182 bytes...
  schannel: sent initial handshake data: sent 182 bytes
  schannel: SSL/TLS connection with github.com port 443 (step 2/3)
  schannel: failed to receive handshake, need more data
  schannel: SSL/TLS connection with github.com port 443 (step 2/3)
  schannel: encrypted data buffer: offset 1436 length 4096
  schannel: encrypted data length: 1338
  schannel: encrypted data buffer: offset 1338 length 4096
  schannel: received incomplete message, need more data
  schannel: SSL/TLS connection with github.com port 443 (step 2/3)
  -- Retry after 15 seconds (attempt #4) ...
  schannel: encrypted data buffer: offset 3492 length 4096
  schannel: sending next handshake data: sending 126 bytes...
  schannel: SSL/TLS connection with github.com port 443 (step 2/3)
  schannel: encrypted data buffer: offset 51 length 4096
  schannel: SSL/TLS handshake complete
  schannel: SSL/TLS connection with github.com port 443 (step 3/3)
  schannel: incremented credential handle refcount = 1
  schannel: stored credential handle in session cache
  GET /ruslo/gsl/archive/v1.16.tar.gz HTTP/1.1

  Host: github.com

  User-Agent: curl/7.44.0

  Accept: */*



  schannel: client wants to read 16384 bytes
  schannel: encdata_buffer resized 17408
  schannel: encrypted data buffer: offset 0 length 17408
  schannel: encrypted data got 1229
  schannel: encrypted data buffer: offset 1229 length 17408
  schannel: decrypted data length: 1200
  schannel: decrypted data added: 1200
  schannel: decrypted data cached: offset 1200 length 16384
  schannel: encrypted data buffer: offset 0 length 17408
  schannel: decrypted data buffer: offset 1200 length 16384
  schannel: schannel_recv cleanup
  schannel: decrypted data returned 1200
  schannel: decrypted data buffer: offset 0 length 16384
CUSTOMBUILD : The requested URL returned error : 404 Not Found [C:\tools\hunter\_Base\0a63c66\2e0e6b1\a812237\Build\GSL\Build\GSL-Release.vcxproj]
  Closing connection 0
  schannel: shutting down SSL/TLS connection with github.com port 443
  schannel: clear security context handle
  schannel: decremented credential handle refcount = 0

    --- LOG END ---
```

**Comment by ruslo** [comment] 2016-09-24 20:20
Looks like I did remove this repository from my profile.

**Comment by ruslo** [comment] 2016-09-24 22:45
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.992
* https://travis-ci.org/ingenue/hunter/builds/162495836

**Comment by grisevg** [comment] 2016-09-25 23:15
Considering that GSL is just a bunch of include headers, does it really needs a separate repo?

**Comment by ruslo** [comment] 2016-09-26 07:56
Tests passed:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.997
* https://travis-ci.org/ingenue/hunter/builds/162622042

Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1001
* https://travis-ci.org/ingenue/hunter/builds/162711432

**Comment by ruslo** [comment] 2016-09-26 08:04
> Considering that GSL is just a bunch of include headers, does it really needs a separate repo?

What do you mean by "separate repo"? If I want to apply temporary fixes I need to have fork, right?

**Comment by grisevg** [comment] 2016-09-26 09:39
Oh, that's confusing... I was talking about a different `GSL`: https://github.com/Microsoft/GSL
Why would they name it the same X_X

**Comment by ruslo** [comment] 2016-09-26 11:44
> Uploading

Done. This issue fixed in https://github.com/ruslo/hunter/releases/tag/v0.15.33

> Oh, that's confusing... I was talking about a different GSL: https://github.com/Microsoft/GSL

Hm, I see. Please open separate issue for this one.

> Why would they name it the same X_X

There is no central registry for C++ packages so there is no collisions control :)

**Closed by ruslo** 2016-09-26 11:44 UTC
Labels: bug

**Comment by grisevg** [comment] 2016-09-26 12:02
@ruslo How would you handle two packages named the same in hunter? Maybe naming it `MicrosoftGSL` will do...

**Comment by ruslo** [comment] 2016-09-26 12:23
> How would you handle two packages named the same in hunter?

@grisevg Hunter will not handle it, all packages should have different names.

> Maybe naming it MicrosoftGSL will do

Yes, as a workaround. However both packages will install files to `gsl/gsl_*.h`, which is the main problem. Related feature request: https://github.com/ruslo/hunter/issues/275

**Comment by grisevg** [comment] 2016-09-26 12:30
Well Microsoft's GSL files don't have `.h` extension so it should work for now, but of course its can cause problems and confusion later
