### ISSUE TITLE
Altering CFLAGS and CXXFLAGS, trying to build libcurl for iOS

### ISSUE THREAD

**Issue by arrtchiu** [ruslo/hunter#821] opened 2017-06-05 14:51 UTC
Hoping for some tips on a problem - I'd love to contribute back to this project but would greatly benefit from some pointers to get started understanding everything :)

Two issues I'd be grateful for help on:
1. Seems the detection of strerror is failing to detect which one is appropriate for iOS. I assume it should be defining `HAVE_POSIX_STRERROR_R` but is failing in the detection stage. Not sure where to begin fixing this so I'd be happy to work around it by manually adding `-DHAVE_POSIX_STRERROR_R` to the compile flags.
2. Need to add `-fembed-bitcode` flag to everything compiled. Again there's probably a better way but during these early stages I'm happy to work around by manually adding it.

I tried what was suggested in [this](https://github.com/ruslo/hunter/issues/803) issue with no luck

```
# invoke with:
# cmake -G Xcode -H. -B_builds -DCMAKE_TOOLCHAIN_FILE=/path/to/polly/ios-10-3.cmake
  cmake_minimum_required(VERSION 3.7.1)
  include("cmake/HunterGate.cmake")
  HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.18.66.tar.gz"
    SHA1 "26028d26e2a9e0496fd7c896fa04e05b309ab6fd"
  )
  hunter_add_package(cURL)
  hunter_cmake_args(cURL CMAKE_ARGS
                    CMAKE_C_FLAGS="-DHAVE_POSIX_STRERROR_R -fembed-bitcode"
                    CMAKE_CXX_FLAGS="-DHAVE_POSIX_STRERROR_R -fembed-bitcode")
  add_library(foo foo.cpp)
```

Relevant error here (in case fixing the root cause is better/easier):
```
CompileC /Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/CURL.build/Release-iphoneos/libcurl.build/Objects-normal/armv7/strerror.o lib/strerror.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Source
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Release-iphoneos\" -DBUILDING_LIBCURL -DHAVE_CONFIG_H -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk -fstrict-aliasing -Wdeprecated-declarations -miphoneos-version-min=10.3 -Wno-sign-conversion -Wno-infinite-recursion -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/Release-iphoneos/include -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/include/curl -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Source/include -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Install/include -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/../include -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Source/lib/.. -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Source/lib/../include -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/.. -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Source/lib -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/CURL.build/Release-iphoneos/libcurl.build/DerivedSources/armv7 -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/CURL.build/Release-iphoneos/libcurl.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/Release-iphoneos -DNDEBUG -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/include/curl -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Source/include -isystem /Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Install/include -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/../include -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Source/lib/.. -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Source/lib/../include -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/.. -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Source/lib -I/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib -MMD -MT dependencies -MF /Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/CURL.build/Release-iphoneos/libcurl.build/Objects-normal/armv7/strerror.d --serialize-diagnostics /Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/CURL.build/Release-iphoneos/libcurl.build/Objects-normal/armv7/strerror.dia -c /Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Source/lib/strerror.c -o /Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/CURL.build/Release-iphoneos/libcurl.build/Objects-normal/armv7/strerror.o
/Users/x/.hunter/_Base/26028d2/d2a5da9/bf75c7e/Build/CURL/Source/lib/strerror.c:32:6: error: "strerror_r MUST be either POSIX, glibc or vxworks-style"
#    error "strerror_r MUST be either POSIX, glibc or vxworks-style"
     ^
1 error generated.
```

**Comment by ruslo** [comment] 2017-06-05 15:08
> I tried what was suggested in this issue with no luck

https://github.com/ruslo/hunter/issues/803 is about autotools projects. Even if it's about C/C++ compile flags the issue is quite different.

> CMAKE_C_FLAGS="-DHAVE_POSIX_STRERROR_R -fembed-bitcode"

It should be `"CMAKE_C_FLAGS=-DHAVE_POSIX_STRERROR_R -fembed-bitcode"`, see:
* http://cgold.readthedocs.io/en/latest/tutorials/variables/regular.html#quotes

> Relevant error here (in case fixing the root cause is better/easier)

Since I don't see `-fembed-bitcode` flag at all I think we can't use `CMAKE_C_FLAGS` hack with Xcode. The right way to apply flags to 3rd party packages globally is to use toolchain. Is `-fembed-bitcode` the flag added by `CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE`? In this case it can be just `set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE TRUE)`. Currently this feature is disabled:
* https://github.com/ruslo/polly/blob/344018e298861fe4f8158c4274deafdbaab4ac04/os/iphone.cmake#L149

Please submit request to Polly, need to run few tests.

> Seems the detection of strerror is failing to detect which one is appropriate for iOS. I assume it should be defining HAVE_POSIX_STRERROR_R but is failing in the detection stage. Not sure where to begin fixing this so I'd be happy to work around it by manually adding -DHAVE_POSIX_STRERROR_R to the compile flags

It should be fixed in CMakeLists.txt of CURL, hunterized fork is here:
* https://github.com/hunter-packages/curl

**Comment by ruslo** [comment] 2017-06-14 10:43
iOS + CURL (one architecture) works for now, closing.

**Closed by ruslo** 2017-06-14 10:43 UTC
Labels: discussion
