### ISSUE TITLE
cannot find -lpthreads when add package openssl.

### ISSUE THREAD

**Issue by mxito3** [ruslo/hunter#1719] opened 2019-01-24 03:57 UTC
I use 
```
hunter_add_package(OpenSSL)
find_package(OpenSSL REQUIRED)
```
 to add openssl  for my project. But I got  `/usr/bin/ld.gold: error: cannot find -lpthreads` in CMakeError.log. In order to decrease problems, I tried 
```
sudo apt-get install libpthread-stubs0-dev
``` 
But don't make any affect.

os:Ubuntu 16.04

**Comment by headupinclouds** [comment] 2019-01-24 15:23
Can you provide a small minimal example to reproduce the issue, including the build command and any toolchain you are using?

As a workaround, you could try explicitly linking through CMake's imported threads package:
```
find_package(Threads REQUIRED)
target_link_libraries(app Threads::Threads)
```

If there is a problem, it would be nice to get it fixed in the OpenSSL package.

**Comment by mxito3** [comment] 2019-01-30 12:02
@headupinclouds not fixed by `find_package(Threads REQUIRED)
target_link_libraries(app Threads::Threads)`. Finally, I  use absolute path of "Openssl::Crypto" like `target_link_libraries(${PROJECT_NAME} /usr/lib/x86_64-linux-gnu/libcrypto.so)` solved the problem.

**Comment by headupinclouds** [comment] 2019-01-30 16:06
Can you post a link to a small minimal example that can be used to reproduce the issue and shows exactly what you are doing?

> target_link_libraries(${PROJECT_NAME} /usr/lib/x86_64-linux-gnu/libcrypto.so)

Typically you should use logical CMake build targets instead of the direct library paths, and you should use the hunter libs instead of the system libs.

I just tried the OpenSSL example directly in hunter with a gcc toolchain on Ubuntu 18.04 from [polly](http://github.com/ruslo/polly) and it worked fine:

```
cd hunter
TOOLCHAIN=gcc PROJECT_DIR=examples/OpenSSL ./jenkins.py
```

You want something like this:

```
target_link_libraries(foo PUBLIC OpenSSL::SSL OpenSSL::Crypto)
```

See:

https://github.com/ruslo/hunter/blob/94c0cce97f4f72b58c2b70b3711a92f6ecb41c04/examples/OpenSSL/CMakeLists.txt#L12-L16

**Comment by mxito3** [comment] 2019-01-31 03:16
@headupinclouds I have upload code to [https://github.com/mxito3/test](https://github.com/mxito3/test). 

And I add openssl here.
[https://github.com/mxito3/test/blob/c7cc8e4dbc0e0fd011ea789457303d132f8c3342/CMakeLists.txt#L89-L90](https://github.com/mxito3/test/blob/c7cc8e4dbc0e0fd011ea789457303d132f8c3342/CMakeLists.txt#L89-L90)
![image](https://user-images.githubusercontent.com/25946298/52028216-30053a00-2549-11e9-9a60-e2acaf6365d2.png)

Used openssl here.[https://github.com/mxito3/test/blob/c7cc8e4dbc0e0fd011ea789457303d132f8c3342/permissionController/CMakeLists.txt#L1-L5](https://github.com/mxito3/test/blob/c7cc8e4dbc0e0fd011ea789457303d132f8c3342/permissionController/CMakeLists.txt#L1-L5)
![image](https://user-images.githubusercontent.com/25946298/52028245-46ab9100-2549-11e9-9673-7e9aa381ac8b.png)


Used toolchain here.
https://github.com/mxito3/test/blob/c7cc8e4dbc0e0fd011ea789457303d132f8c3342/CMakeLists.txt#L16
![image](https://user-images.githubusercontent.com/25946298/52028278-5fb44200-2549-11e9-9449-427a1d7ff1e9.png)

repo of toolchain is https://github.com/ethereum/cable

build command is 
```
mkdir build 
cd build 
cmake ..  
make
```

**Comment by ruslo** [comment] 2019-01-31 07:53
Threads added here:
- https://github.com/ruslo/hunter/blob/v0.23.93/cmake/find/FindOpenSSL.cmake#L376

I think the problem is that somewhere custom `FindOpenSSL.cmake` added to `CMAKE_MODULE_PATH` and `FindOpenSSL.cmake` from Hunter is ignored. Please add `HUNTER_STATUS_DEBUG=ON` to configure and make sure this line is printed:
- https://github.com/ruslo/hunter/blob/v0.23.93/cmake/find/FindOpenSSL.cmake#L58-L60

Reporting bugs intruction is here:
- https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs

**Comment by mxito3** [comment] 2019-02-01 08:19
Now this line is printed:

![image](https://user-images.githubusercontent.com/25946298/52110844-e138cc80-263c-11e9-9a1c-ca5215cf6b64.png)


But still with an error while link.

![image](https://user-images.githubusercontent.com/25946298/52110810-c6feee80-263c-11e9-918b-dc1c343ca29d.png)

**Comment by ruslo** [comment] 2019-02-04 18:08
> But still with an error while link

What is the error message? `OpenSSL::SSL-NOTFOUND` looks very suspicious, please post full logs. Also my advice will be to start with plain simple `hunter_add_package(OpenSSL)` and `find_package(OpenSSL REQUIRED)`, without all extra modules you have added.

**Comment by ruslo** [comment] 2019-08-25 12:12
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst

**Closed by ruslo** 2019-08-25 12:12 UTC
Labels: discussion
