### ISSUE TITLE
OpenSSL Android support

### ISSUE THREAD

**Issue by jneidlinger** [ruslo/hunter#260] opened 2015-10-22 01:59 UTC
Getting this linker error whenever trying to use the OpenSSL with Android toolchains.

```
ld: error: /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libssl.a: no archive symbol table (run ranlib)
ld: error: /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libcrypto.a: no archive symbol table (run ranlib)
```

Here is the error in full context:

```
[ 80%] Linking CXX shared library libqmlexample.so
/Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/qmlexample.dir/link.txt --verbose=1
/Users/jneidlinger/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc  -fPIC -fexceptions -frtti -Wno-psabi --sysroot=/Users/jneidlinger/android-ndk-r10e/platforms/android-19/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -std=c++11  -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now  -shared -Wl,-soname,libqmlexample.so.1.0 -o libqmlexample.so.1.0 CMakeFiles/qmlexample.dir/main.cpp.o CMakeFiles/qmlexample.dir/qmlexample_automoc.cpp.o /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libssl.a /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libcrypto.a -ldl /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libQt5Widgets.so /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libQt5Quick.so /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/plugins/qmltooling/libqmldbg_tcp.so -lGLESv2 /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libQt5Gui.so /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libQt5Qml.so /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libQt5Network.so /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libQt5Core.so  "/Users/jneidlinger/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a" "/Users/jneidlinger/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a" -lm
/Users/jneidlinger/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libssl.a: no archive symbol table (run ranlib)
/Users/jneidlinger/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: /Users/jneidlinger/.hunter/_Base/a25a7fa/aef40ea/f081f0d/Install/lib/libcrypto.a: no archive symbol table (run ranlib)
collect2: error: ld returned 1 exit status
make[2]: *** [libqmlexample.so.1.0] Error 1
make[1]: *** [CMakeFiles/qmlexample.dir/all] Error 2
make: *** [all] Error 2
```

It looks like maybe the OpenSSL libs aren't build under the android/arm toolchain?

Built using the following polly build.py call

```
build.py --toolchain android-ndk-r10e-api-19-armeabi-v7a-neon --clear --verbose --jobs 10
```

Here is a SSCCE, build it using the above build.py call to reproduce the issue:
https://cudadrive.com/9WtEbskOhTCVEjIH
##

**Comment by ruslo** [comment] 2015-10-22 03:10
> It looks like maybe the OpenSSL libs aren't build under the android/arm toolchain?

Yep, actually I've never tried it. Need to create new build scheme.

> Here is a SSCCE, build it using the above build.py call to reproduce the issue

Got the same error with this example: https://github.com/ruslo/hunter/blob/master/examples/OpenSSL/CMakeLists.txt Since there are no arm specific flags passed to Configure the resulting library simply built for usage on host machine.

Will try to adapt this instructions: https://wiki.openssl.org/index.php/Android
Let me know if you have a better idea :)

**Comment by jneidlinger** [comment] 2015-10-22 03:19
script for building OpenSSL under android NDK

```
#Configure OpenSSL
cd $SSLPATH
./Configure android no-asm no-shared no-cast no-idea no-camellia no-whirpool
EXITCODE=$?
if [ $EXITCODE -ne 0 ]; then
	echo "Error running the ssl configure program"
	cd $PWD
	exit $EXITCODE
fi

cd $SCRIPTPATH
$NDK_ROOT/ndk-build -j$JOBS -C $SCRIPTPATH ssl crypto
EXITCODE=$?
if [ $EXITCODE -ne 0 ]; then
	echo "Error building the libssl and libcrypto"
	cd $PWD
	exit $EXITCODE
fi
```
(referenced from https://github.com/gcesarmza/curl-android-ios/blob/master/curl-compile-scripts/build_Android.sh)

**Comment by rcdailey** [comment] 2016-09-12 16:18
I'm currently working on adding android support to Hunter's OpenSSL scripts. I'd like feedback from @ruslo on the best way to incorporate this: https://wiki.openssl.org/images/7/70/Setenv-android.sh

Basically before running `./config`, I need to:

```
chmod a+x ./setenv-android.sh
source ./setenv-android.sh
```

But even before *that*, I need to either download the file and position it in the OpenSSL source dir (the temp one downloaded & extracted by hunter) *or* possibly just package `setenv-android.sh` with Hunter itself and copy it over.

Advice on the best approach would be helpful. Thank you.

**Comment by ruslo** [comment] 2016-09-12 16:40
> I'd like feedback from @ruslo on the best way to incorporate this: https://wiki.openssl.org/images/7/70/Setenv-android.sh

You need to introduce new [OpenSSL build scheme](https://github.com/ruslo/hunter/tree/master/cmake/projects/OpenSSL/schemes) and add it to `hunter.cmake`:
```cmake
if(ANDROID)
  hunter_pick_scheme(DEFAULT url_sha1_openssl_android)
endif()
```

Android specific variables will be set by toolchain you should use those CMake variables to initialize environment variables. Also as I already mentioned the set of variables will be changed with new CMake version, you can try updated Android toolchain from branch [new.android](https://github.com/ruslo/polly/tree/new.android).

Another peculiarity about environment variables is that they will be set by CMake only on generate step and not for build step (see [example](http://cgold.readthedocs.io/en/latest/tutorials/variables/environment.html#configure-step)) hence if you're creating ExternalProject_Add and want to set environment variables for different steps you can't just do `set(ENV{...})`. You should configure file with environment variables and run it, see Qt approach as example: https://github.com/ruslo/hunter/blob/master/cmake/projects/Qt/schemes/url_sha1_qt.cmake.in (qt-configure, qt-build, qt-install).

> Basically before running ./config, I need to:

There are too much variables hardcoded there. It will be easier to rewrite this file in terms on CMake instead of reusing it. Also it's a shell script that will not work on Windows, CMake code will work everywhere.

**Comment by rcdailey** [comment] 2016-09-12 17:23
Would it be advisable to make a copy of `url_sha1_openssl.cmake.in` and base my android changes off of that? There's a lot of setup work going on there and I'm not fully sure of which parts I need to keep. I assume just the ExternalProject_Add() related stuff will be different.

**Comment by ruslo** [comment] 2016-09-12 17:39
>  Would it be advisable to make a copy of url_sha1_openssl.cmake.in and base my android changes off of that?

Yes, I guess so.

> I assume just the ExternalProject_Add() related stuff will be different

It will be a little bit more complex because of environment variables. See my notes above.

**Comment by rcdailey** [comment] 2016-09-12 17:39
Also, other than doing something like `CONFIGURE_COMMAND "set CC=@CMAKE_C_COMPILER" && "set CXX=@CMAKE_CXX_COMPILER"`, I'm not sure how else I'm supposed to tell the OpenSSH `make` command where to find the `gcc` compiler. It doesn't seem to have an input argument to `./config` to specify the toolchain to use.

If you know differently let me know. Thanks for your advice.

**Comment by ruslo** [comment] 2016-09-12 17:46
> Also, other than doing something like CONFIGURE_COMMAND "set CC=@CMAKE_C_COMPILER" && "set CXX=@CMAKE_CXX_COMPILER"

Sorry don't know too. Also please don't use `set CC=...` syntax since it's doesn't work well in some cases. It should be written in terms of CMake commands (i.e. `set(ENV{CC} @CMAKE_C_COMPILER@)`). There are some usage of this in Hunter but it will be removed in future, see https://github.com/ruslo/hunter/issues/246.

**Comment by rcdailey** [comment] 2016-09-12 17:48
But according to one of your last responses, we cannot do `set()`; this needs to be a command passed to configure or build steps in `ExternalProject_Add()`, correct?

**Comment by ruslo** [comment] 2016-09-12 18:01
> But according to one of your last responses, we cannot do set()

I mean we can't do

```cmake
set(ENV{CC} @CMAKE_C_COMPILER@)
ExternalProject_Add(
   CONFIGURE_COMMAND
   # some command that need CC environment variable
   BUILD_COMMAND
   # some command that need CC environment variable
)
```

because `set(ENV{CC}` will set variable on generate step but *_COMMAND is a part of the build step, hence CC will not be visible. You can create separate CMake file:
```cmake
set(ENV{CC} @CMAKE_C_COMPILER@)
execute_process(COMMAND ...) # your build configure/build command that will use CC environment variable
```

and run this script on *_COMMAND step:
```cmake
ExternalProject_Add(
   BUILD_COMMAND
   ${CMAKE_COMMAND} -P "/path/to/build-step.cmake"
)
```

There are some peculiarities, like I said before please take a look at Qt build scheme.

**Comment by bezigon** [comment] 2016-12-06 07:52
OpenSSL for Android is broken, the latest ndk and hunter release is used.
```
/Users/bezigon/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ssl: no archive symbol table (run ranlib)
/Users/bezigon/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: crypto: no archive symbol table (run ranlib)
openssl.o:openssl.c:function function_LHASH_HASH: error: undefined reference to 'lh_strhash'
openssl.o:openssl.c:function do_cmd: error: undefined reference to 'lh_retrieve'
openssl.o:openssl.c:function do_cmd: error: undefined reference to 'EVP_get_digestbyname'
openssl.o:openssl.c:function do_cmd: error: undefined reference to 'EVP_get_cipherbyname'
openssl.o:openssl.c:function do_cmd: error: undefined reference to 'BIO_new_fp'
openssl.o:openssl.c:function do_cmd: error: undefined reference to 'EVP_CIPHER_do_all_sorted'
```

I solved the problem:
```
export PATH=/Users/bezigon/android-toolchains/arm-linux-androideabi/bin:$PATH
CROSS_COMPILE=arm-linux-androideabi- CC=${CROSS_COMPILE}gcc ./Configure dist --prefix=`pwd`/arm-linux-androideabi
make -j8
```

But this is not a hunter's way.

**Comment by ruslo** [comment] 2016-12-06 08:01
> the latest ndk and hunter release is used

Can you give an exact versions just to be sure?

**Comment by bezigon** [comment] 2016-12-06 08:16
```
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.16.36.tar.gz"
    SHA1 "a47baf7a23fee038812baa7d6a9362ca1770b6ed"
)

NDK 13.1.3345770 (Installed in Android Studio 2.2.2 on Mac OS X 10.11.6)
```

**Comment by bezigon** [comment] 2016-12-06 08:20
These android toolchains I installed separately, using the script `$NDK/build/tools/make_standalone_toolchain.py`

**Comment by ruslo** [comment] 2016-12-06 08:25
> These android toolchains I installed separately, using the script $NDK/build/tools/make_standalone_toolchain.py

Never have used them. Just for your info it was tested with Polly toolchains (based on `taka-no-me` toolchain). @bezigon I'm testing it now on my local machine.

**Comment by bezigon** [comment] 2016-12-06 08:36
> Just for your info it was tested with Polly toolchains (based on taka-no-me toolchain).
So am I. Mainly, I needed some of these packages: CURL, CppNetlib.URI, Poco C++ (they have http-client), and i can't get them because of OpenSSL.

**Comment by ruslo** [comment] 2016-12-06 08:44
@bezigon I get it. You're using OSX host, it doesn't work, see:
* https://github.com/ingenue/hunter/blob/2b2d8aea4432d3a3f1bae0cee4fc3157b30256a6/.travis.yml#L70-L73

As a workaround you can build same toolchain on Linux and upload binaries to server. Then try same toolchain on OSX, toolchain-id should match and you will get binaries without triggering build instructions.

> I solved the problem

Actually this one look like a solution. Please patch OpenSSL build scheme and will see if it helps.

**Comment by bezigon** [comment] 2016-12-06 14:37
> As a workaround you can build same toolchain on Linux and upload binaries to server. Then try same toolchain on OSX, toolchain-id should match and you will get binaries without triggering build instructions.

On Ubuntu, after a few of the hours of the initial setup I came finally to its logical conclusion... Nope, I cheated on you :)

```
$ build.py --toolchain android-ndk-r11c-api-21-armeabi-v7a --clear --test --config Debug

[ 75%] Performing build step for 'OpenSSL'
making all in crypto...
make[1]: Entering directory '/home/bezigon/.hunter/_Base/a47baf7/99b5517/e6d3e50/Build/OpenSSL/Source/crypto'
/usr/bin/perl ../util/mkbuildinf.pl "/home/bezigon/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -marm -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -fexceptions -Wa,--noexecstack -march=armv7-a -mandroid -I/include -B/lib -O3 -fomit-frame-pointer -Wall -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM" "android-armv7" >buildinf.h
/home/bezigon/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -I. -I.. -I../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -march=armv7-a -marm -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -fexceptions -Wa,--noexecstack -march=armv7-a -mandroid -I/include -B/lib -O3 -fomit-frame-pointer -Wall -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM   -c -o cryptlib.o cryptlib.c
In file included from cryptlib.c:117:0:
cryptlib.h:62:21: fatal error: stdlib.h: No such file or directory
 # include <stdlib.h>
                     ^
compilation terminated.
<builtin>: recipe for target 'cryptlib.o' failed

$ find / -name 'stdlib.h'

/home/bezigon/android-ndk-r11c/platforms/android-13/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-13/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-13/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-4/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-14/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-14/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-14/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-5/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-23/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-23/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-23/arch-x86_64/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-23/arch-arm64/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-23/arch-mips64/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-23/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-19/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-19/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-19/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-3/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-12/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-12/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-12/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-9/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-9/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-9/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-8/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-18/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-18/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-18/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-24/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-24/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-24/arch-x86_64/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-24/arch-arm64/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-24/arch-mips64/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-24/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-17/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-17/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-17/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-21/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-21/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-21/arch-x86_64/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-21/arch-arm64/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-21/arch-mips64/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-21/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-16/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-16/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-16/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-15/arch-mips/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-15/arch-x86/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/platforms/android-15/arch-arm/usr/include/stdlib.h
/home/bezigon/android-ndk-r11c/sources/android/support/include/stdlib.h
/home/bezigon/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/tr1/stdlib.h
/home/bezigon/android-ndk-r11c/sources/cxx-stl/stlport/stlport/stdlib.h
```

Thoughts?

**Comment by ruslo** [comment] 2016-12-06 14:49
Working Travis job:
* https://travis-ci.org/ingenue/hunter/jobs/181586302

Can you try `android-ndk-r10e-api-19-armeabi-v7a-neon` just to be sure that the problem is about NDK version?

**Comment by bezigon** [comment] 2016-12-06 15:42
Same there :(

https://gist.github.com/bezigon/8cfeeabd562a3838a53e477ff9aab3ae

Ubuntu 16.04 LTS x64 minimal environment

**Comment by bezigon** [comment] 2016-12-06 16:12
SUCCESS!!1 I have success with other version of hunter with `android-ndk-r10e-api-19-armeabi-v7a-neon`
```
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.17.3.tar.gz"
    SHA1 "2a2f193860e2cb3b884bce74d85c3f30b1092274"
)
```

**Comment by bezigon** [comment] 2016-12-06 16:14
I will test with other toolchains. Can I move the cache archive to OS X host?

**Comment by ruslo** [comment] 2016-12-06 18:43
@bezigon find the string with toolchain-id, it looks like this:
```
-- [hunter] [ Hunter-ID: e9cc5c6 | Config-ID: f88dcd8 | Toolchain-ID: 5813733 ]
```
what is your value?

> Can I move the cache archive to OS X host?

see https://docs.hunter.sh/en/latest/faq/why-binaries-from-server-not-used.html#uploading-to-server

**Comment by bezigon** [comment] 2016-12-07 09:15
> If you have shared folder in your network there is no need to use any scripts, you can just set HUNTER_ROOT variable to location of this directory.

OpenSSL doesn't like that. There are errors with `ln` on shared folder.

**Comment by ruslo** [comment] 2016-12-07 09:20
> There are errors with `ln` on shared folder

what kind of error?

**Comment by bezigon** [comment] 2016-12-07 10:38
> what kind of error?

```
making links in crypto...
make[1]: Entering directory '/media/sf_.hunter/_Base/2a2f193/040070c/d52c5e1/Build/OpenSSL/Source/crypto'
crypto.h => ../include/openssl/crypto.h [Read-only file system]
opensslv.h => ../include/openssl/opensslv.h [Read-only file system]
opensslconf.h => ../include/openssl/opensslconf.h [Read-only file system]
...
ln: failed to create symbolic link 'bntest.c': Read-only file system
bntest.c => dummytest.c
ln: failed to create symbolic link 'ectest.c': Read-only file system
ectest.c => dummytest.c
ln: failed to create symbolic link 'ecdsatest.c': Read-only file system
ecdsatest.c => dummytest.c
ln: failed to create symbolic link 'ecdhtest.c': Read-only file system
ecdhtest.c => dummytest.c
ln: failed to create symbolic link 'ideatest.c': Read-only file system
ideatest.c => dummytest.c
```

OpenSSL on shared folder: https://gist.github.com/bezigon/2ae95a0377816b57015de25b869f3e9a

**Comment by bezigon** [comment] 2016-12-07 10:56
> @bezigon find the string with toolchain-id, it looks like this:
> `-- [hunter] [ Hunter-ID: e9cc5c6 | Config-ID: f88dcd8 | Toolchain-ID: 5813733 ]`
> what is your value?

I can't give it because every time the `Toolchain-ID` randomizes, or I'm wrong?

**Comment by ruslo** [comment] 2016-12-07 11:04
> ln: failed to create symbolic link 'ideatest.c': Read-only file system

@bezigon looks like you don't have an access to the folders.

> I can't give it because every time the Toolchain-ID randomizes, or I'm wrong?

Of course not :) why do you think so? Toolchain-ID is the first 7 digist of SHA1 of file `toolchain.info` ([docs](https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html)). It **may** change from time to time even if toolchain is not changing but in general the value is the same for the same toolchains. In our case toolchain-id for android toolchain should be the same even on different hosts (OSX and Linux).

Also just for your info `https://github.com/ruslo/hunter/archive/v0.16.36.tar.gz` and `https://github.com/ruslo/hunter/archive/v0.17.3.tar.gz` work differently for Android, first version designed to work with `taka-no-me` and second version designed to be used with native Android support from CMake 3.7.1+ (that's why minor version changed). For OpenSSL you may not see the difference, build scheme should work for both. But in general internal code changed and toolchain-id will not be the same for the same toolchain.

**Comment by ruslo** [comment] 2016-12-07 11:06
I think the original issue is fixed so I will close this one. @bezigon please open another issue if you have any questions further.

**Closed by ruslo** 2016-12-07 11:06 UTC
Labels: broken package, enhancement
