### ISSUE TITLE
HUNTER_JOBS_NUMBER set to very large number, and can't be overridden in certain contexts

### ISSUE THREAD

**Issue by edtanous** [ruslo/hunter#668] opened 2017-02-08 19:41 UTC
In the function hunter_jobs_number, hunter is determining my system to have 3872 logical cores and is therefore setting the jobs number incorrectly for boost.

Based on the comment in "hunter_jobs_number.cmake" it references a gitlab issue against cmake that claims number of logical cores is actually reporting logical cores per physical core.  On my system, this does not seem to be the case in either cmake 3.5 or 3.7, and other people report it working correctly.

The gitlab bug against cmake also has reports of it working inconsistently on different OSes and Processors.

cmake_host_system_information(RESULT l_cores QUERY NUMBER_OF_LOGICAL_CORES)
returns 88
cmake_host_system_information( RESULT p_cores QUERY NUMBER_OF_PHYSICAL_CORES)
returns 44.

For reference, I am on an Ubuntu 16.04 x64 system, running dual socket e5-2699s.  The numbers reported above are correct for my system.

This bug causes a very unfortunate issue when building boost components;  url_sha1_boost_library.cmake.in uses hunter_jobs_number to determine the result of the -j option sent to b2.  This becomes an issue because b2 only allows values in the range 0-256, so the compilation fails in this case.  Attempting to override on the command line with either HUNTER_JOBS_NUMBER or HUNTER_JOBS_OPTION seems to have no effect, as the cmake library build jobs aren't being passed these values, and the number is being recomputed.

The available resolutions I see are as follows:
1. Edit hunter_jobs_number.cmake to use the larger of NUMBER_OF_LOGICAL_CORES and NUMBER_OF_PHYSICAL_CORES instead of multiplying them.  This will at least use as many cores are are on the machine, and work around the bug, although machines where NUMBER_OF_LOGICAL_CORES is actually equal to logical cores per core would not use their potential hardware.  This is (I think) the ideal option, as it maintains backward compatibility with broken cmake versions, while not breaking it for correct cmake versions.
2. Clamp the number of jobs to be passed to b2 to the supported max (256) before passing the value through.  This would spin up more jobs than necessary, and would sub optimal for build times, but would solve the issue (so long as all system ram is not exhausted)
3. Pass HUNTER_JOBS_OPTION through to the cmake library build, so that the incorrect behavior can be overridden by manually setting the option on the command line.  This has the disadvantage of not solving root problem, only providing a workaround.

Relevant part of a build output is below:
[ 75%] Performing build step for 'Boost-random'
cd /home/ed/.hunter/_Base/ffd5784/e3e2f82/e1266bb/Build/Boost/__random/Source && ./b2 "-d+2 --debug-configuration" -a link=static threading=multi variant=debug,release --layout=tagged toolset=gcc --user    -config=/home/ed/.hunter/_Base/ffd5784/e3e2f82/e1266bb/Build/Boost/__random/Build/boost.user.jam --wi    th-random -j 3872
CMakeFiles/Boost-random.dir/build.make:117: recipe for target 'Boost-random-prefix/src/Boost-random-s    tamp/Boost-random-build' failed

**Comment by ruslo** [comment] 2017-02-08 22:51
> Edit hunter_jobs_number.cmake to use the larger of NUMBER_OF_LOGICAL_CORES and NUMBER_OF_PHYSICAL_CORES instead of multiplying them

Sounds good. Please add a warning message in case of sanity violation, like when NUMBER_OF_PHYSICAL_CORES less than NUMBER_OF_LOGICAL_CORES.

> Clamp the number of jobs to be passed to b2 to the supported max (256) before passing the value through

Sounds good. Plus warning message about `b2` limitation in case HUNTER_JOBS_OPTION is bigger than `256`. It would be nice to have a reference to official documentation too.

> Pass HUNTER_JOBS_OPTION through to the cmake library build, so that the incorrect behavior can be overridden by manually setting the option on the command line

I think it's already passed. Probably the problem is about using this option only for the first level dependencies, and not for dependencies of dependencies. Can be fixed in `hunter_download` module, "grep" for the HUNTER_DOWNLOAD_TOOLCHAIN variable.

**Comment by rcdailey** [comment] 2017-07-13 20:59
This is a regression most likely caused by PR #658, where the calculation is doing:

    physical_core_count * logical_core_count

This logic is incorrect. Per [the linked kitware issue](https://gitlab.kitware.com/cmake/cmake/issues/16594), they ultimately went with "total logical cores on system", not per physical core. As it is now the multiplication is incorrect. For example, I have 8 logical cores on my system (and CMake returns 8) but the Hunter cmake code does 4 * 8. So it's using 32 instead of 8.

See the latest [CMake documentation](https://cmake.org/cmake/help/v3.7/command/cmake_host_system_information.html?highlight=number_of_logical_cores) for correct behavior (note it does not mention **per physical core** anywhere).

**Comment by ruslo** [comment] 2018-05-10 20:18
Fixed in https://github.com/ruslo/hunter/releases/tag/v0.20.72

**Closed by ruslo** 2018-05-10 20:18 UTC
Labels: enhancement
