### ISSUE TITLE
Local vs system includes priority

### ISSUE THREAD

**Issue by alamaison** [ruslo/hunter#368] opened 2016-03-23 22:26 UTC
I have a project, [Comet](https://github.com/alamaison/comet), that uses Hunter to build Boost.Test.  Comet is also in the Hunter it uses to get Boost.  The tests depend on the local 'comet' target and therefore should pick up the include path from the usage requirements, which they do.  However because they use Boost, they also get the Hunter `Install/include` path which contains another set of Comet headers - the wrong set!  For some reason, the `Install/include` set always come first in the include path.

Do you have any advice on how to test such a project?
##

**Comment by ruslo** [comment] 2016-03-24 06:54
> Do you have any advice on how to test such a project?

Local includes should appear first. Also this is true not only for Hunter or CMake but for any kind of build. The reason is the same - you may have headers of the package installed in root already.

>  For some reason, the Install/include set always come first in the include path

What is the reason?

I've tried to add extra local directory to lookup in [examples/GTest](https://github.com/ruslo/hunter/blob/master/examples/GTest/CMakeLists.txt) and local directory comes first in all variants:

```cmake
add_executable(foo foo.cpp)
target_link_libraries(foo GTest::main)
include_directories("${CMAKE_CURRENT_BINARY_DIR}")
```

```cmake
include_directories("${CMAKE_CURRENT_BINARY_DIR}")
add_executable(foo foo.cpp)
target_link_libraries(foo GTest::main)
```

```cmake
add_executable(foo foo.cpp)
target_link_libraries(foo GTest::main)
target_include_directories(foo PUBLIC "${CMAKE_CURRENT_BINARY_DIR}")
```

```cmake
add_executable(foo foo.cpp)
target_include_directories(foo PUBLIC "${CMAKE_CURRENT_BINARY_DIR}")
target_link_libraries(foo GTest::main)
```

**Comment by alamaison** [comment] 2016-03-24 08:33
I was trying to avoid specifying the local include path directly like that. The comet target already knows it's own include path so the tests should just pick it up from usage requirements when linked to comet. In fact comet is header only so 'linking' comet is done just to pick up this include path

**Comment by ruslo** [comment] 2016-03-24 10:10
Okay now I see. Can reproduce it by:

```cmake
add_library(foo-includes INTERFACE)
target_include_directories(foo-includes INTERFACE "${CMAKE_CURRENT_BINARY_DIR}")

add_executable(foo foo.cpp)
target_link_libraries(foo GTest::main)

target_link_libraries(foo foo-includes) # after GTest
```

Fix is to link local library first:
```cmake
add_library(foo-includes INTERFACE)
target_include_directories(foo-includes INTERFACE "${CMAKE_CURRENT_BINARY_DIR}")

add_executable(foo foo.cpp)
target_link_libraries(foo foo-includes) # before GTest

target_link_libraries(foo GTest::main)
```

One idea that came to mind is that includes that marked as `SYSTEM` should always has low priority. But this should be implemented in CMake, probably introducing new policy.

**Comment by alamaison** [comment] 2016-04-02 10:04
Linking the local library first didn't work for me.  Perhaps because I'm linking boost via `target_include_directories` (for non-Hunter compatibility).  I was able to get it to work by forcing this include order like this:

```cmake
target_include_directories(unit-tests PRIVATE ${Boost_INCLUDE_DIR})
target_link_libraries(unit-tests PRIVATE ${Boost_LIBRARIES})

target_link_libraries(unit-tests PRIVATE comet)
# Force comet target include dirs to come before others (which may included installed comet)
target_include_directories(unit-tests
  BEFORE PRIVATE $<TARGET_PROPERTY:comet,INTERFACE_INCLUDE_DIRECTORIES>)
```

It seems that `target_includes_directories` take precedence over includes from `target_link_libraries`, no matter whether you put the call before or after.  `target_link_libraries` can never win.

**Comment by ruslo** [comment] 2016-04-02 10:23
> It seems that target_includes_directories take precedence over includes from target_link_libraries, no matter whether you put the call before or after

Okay, I see, thanks for details. This is very tricky...

**Comment by ruslo** [comment] 2016-04-08 06:36
Not the same but related:
* http://www.mail-archive.com/cmake-developers@cmake.org/msg16054.html

haven't tried it yet but looks like things work pretty wrong by default

**Comment by ruslo** [comment] 2016-04-15 16:06
One more link:
* http://www.mail-archive.com/cmake@cmake.org/msg54573.html

**Comment by ruslo** [comment] 2018-02-03 08:13
Not directly related to Hunter, moved to https://github.com/ruslo/CGold/issues/26.

**Closed by ruslo** 2018-02-03 08:13 UTC
Labels: discussion
