### ISSUE TITLE
Boost bootstrap fails with Ninja on Windows

### ISSUE THREAD

**Issue by chfast** [ruslo/hunter#1223] opened 2017-11-24 13:26 UTC
```
> cat C:/.hunter/_Base/b96750b/2fea431/59ec5bb/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-*.log
CMake Error at C:/.hunter/_Base/b96750b/2fea431/59ec5bb/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake:9 (message):
  Command failed (The system cannot find the file specified):

   'b2' '--layout=tagged' '-d0' 'install' '--without-atomic' '--without-chrono' '--without-container' '--without-context' '--without-coroutine' '--without-coroutine2' '--without-date_time' '--without-exception' '--without-fiber' '--without-filesystem' '--without-graph' '--without-graph_parallel' '--without-iostreams' '--without-locale' '--without-log' '--without-math' '--without-metaparse' '--without-mpi' '--without-program_options' '--without-python' '--without-random' '--without-regex' '--without-serialization' '--without-signals' '--without-system' '--without-test' '--without-thread' '--without-timer' '--without-type_erasure' '--without-wave' '--prefix=C:/.hunter/_Base/b96750b/2fea431/59ec5bb/Build/Boost/Install' '--ignore-site-config'
```

```
> cat C:/.hunter/_Base/b96750b/2fea431/59ec5bb/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-configure-*.log
Building Boost.Build engine

Failed to build Boost.Build engine.
Please consult bootstrap.log for further diagnostics.

You can try to obtain a prebuilt binary from

   http://sf.net/project/showfiles.php?group_id=7586&package_id=72941

Also, you can file an issue at http://svn.boost.org
Please attach bootstrap.log in that case.
```

```
> cat C:\.hunter\_Base\b96750b\2fea431\59ec5bb\Build\Boost\Source\bootstrap.log
###
### Using 'vc14' toolset.
###

\@\ C:\.hunter\_Base\b96750b\2fea431\59ec5bb\Build\Boost\Source\tools\build\src\engine
> \if exist bootstrap rd /S /Q bootstrap

\@\ C:\.hunter\_Base\b96750b\2fea431\59ec5bb\Build\Boost\Source\tools\build\src\engine
> \md bootstrap

\@\ C:\.hunter\_Base\b96750b\2fea431\59ec5bb\Build\Boost\Source\tools\build\src\engine
> \cl /nologo /RTC1 /Zi /MTd /Fobootstrap/ /Fdbootstrap/ -DNT -DYYDEBUG -wd4996 kernel32.lib advapi32.lib user32.lib /Febootstrap\jam0  command.c compile.c constants.c debug.c execcmd.c execnt.c filent.c frames.c function.c glob.c hash.c hdrmacro.c headers.c jam.c jambase.c jamgram.c lists.c make.c make1.c object.c option.c output.c parse.c pathnt.c pathsys.c regexp.c rules.c scan.c search.c subst.c timestamp.c variable.c modules.c strings.c filesys.c builtins.c md5.c class.c cwd.c w32_getreg.c native.c modules/set.c modules/path.c modules/regex.c modules/property-set.c modules/sequence.c modules/order.c
command.c
compile.c
constants.c
debug.c
execcmd.c
execnt.c
filent.c
filent.c(488): warning C4477: 'sprintf' : format string '%.*s' requires an argument of type 'int', but variadic argument 1 has type '__int64'
filent.c(488): note: this argument is used as a precision
frames.c
function.c
glob.c
hash.c
hdrmacro.c
headers.c
jam.c
jambase.c
jamgram.c
lists.c
make.c
make1.c
object.c
Generating Code...
Compiling...
option.c
output.c
parse.c
pathnt.c
pathsys.c
regexp.c
rules.c
scan.c
search.c
subst.c
timestamp.c
variable.c
modules.c
strings.c
filesys.c
builtins.c
md5.c
class.c
cwd.c
w32_getreg.c
Generating Code...
Compiling...
native.c
set.c
path.c
regex.c
property-set.c
sequence.c
order.c
Generating Code...

\@\ C:\.hunter\_Base\b96750b\2fea431\59ec5bb\Build\Boost\Source\tools\build\src\engine
> \.\bootstrap\jam0 -f build.jam --toolset=vc14 "--toolset-root=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\ "  clean
build.jam:192: in module scope
*** argument error
* rule toolset ( name command .type ? : opt.out + : opt.define * : flags * : linklibs * )
* called with: ( cc C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe : -o  : -D : -s -O :  )
* extra argument (x86)/Microsoft
build.jam:156:see definition of rule 'toolset' being called

\@\ C:\.hunter\_Base\b96750b\2fea431\59ec5bb\Build\Boost\Source\tools\build\src\engine
> \.\bootstrap\jam0 -f build.jam --toolset=vc14 "--toolset-root=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\ "
build.jam:192: in module scope
*** argument error
* rule toolset ( name command .type ? : opt.out + : opt.define * : flags * : linklibs * )
* called with: ( cc C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe : -o  : -D : -s -O :  )
* extra argument (x86)/Microsoft
build.jam:156:see definition of rule 'toolset' being called

\@\ C:\.hunter\_Base\b96750b\2fea431\59ec5bb\Build\Boost\Source\tools\build\src\engine
> \exit /b 1
```

**Comment by ruslo** [comment] 2017-11-24 13:59
Ninja excluded from testing:
* https://github.com/ingenue/hunter/blob/8f1b4fd8fc8e1eba99f102052254f7bfa6bd2e17/appveyor.yml#L17-L19

Meaning it's a known issue.

**Comment by chfast** [comment] 2017-11-24 14:41
The problem is with this command:
```
\.\bootstrap\jam0 -f build.jam --toolset=vc14 "--toolset-root=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\ "  clean
```
The build tools is confused with spaces in the path. Does this path comes from Hunter?

**Comment by ruslo** [comment] 2017-11-24 14:58
> Does this path comes from Hunter?

I think no since we are not calling `jam0`. Though it doesn't imply that it can't be fixed in Hunter somehow.

**Comment by ruslo** [comment] 2018-03-10 13:02
Closing inactive issue with "Broken package" label, see details:
* https://github.com/ruslo/hunter/wiki/error.external.build.failed

**Closed by ruslo** 2018-03-10 13:02 UTC
Labels: broken package

**Comment by JoshCollins746** [comment] 2018-09-27 05:18
@ruslo I am experiencing this issue with boost v1.68.0-p1. If I understand the previous comments then the issue lies in the boost package itself. Should I open an issue at https://github.com/hunter-packages/boost?Or is the issue perhaps something that needs to be handled in the official package from boost.org?

**Comment by ruslo** [comment] 2018-10-01 13:37
> Should I open an issue at https://github.com/hunter-packages/boost? Or is the issue perhaps something that needs to be handled in the official package from boost.org?

@JoshCollins746 Try to reproduce it without Hunter and report to boost.build project, as an example see https://github.com/boostorg/build/issues/299 .

**Comment by tomjaguarpaw** [comment] 2018-11-20 13:36
Upstream does not seem especially motivated to fix this https://github.com/boostorg/build/issues/239  Is this something that can be worked around in Hunter?

**Comment by ruslo** [comment] 2018-11-20 14:34
> Is this something that can be worked around in Hunter?

@tomjaguarpaw I'm not aware of any workarounds. Also Boost scheme is already too complex, I don't think introducing workarounds is a good idea.
