### ISSUE TITLE
Hunterize CMake instead of single packages

### ISSUE THREAD

**Issue by piribes** [ruslo/hunter#812] opened 2017-05-31 22:48 UTC
Does anyone has ever thought to move hunter stuff into cmake itself?

I mean, if we hack cmake to include `HunterGate.cmake` and call `HunterGate` before `project`, than what is left is to call `hunter_add_package` just before each `find_package` (or `find_library`, in general anything that needs `hunter_add_package` stuff), isn't it?

At this point, this requires no action on the project's cmake files and become a choice that a user has to made. Do you want to use hunter to manage dependencies of your cmake project for this particular build? Just use this cmake fork.

What do you think about that?

**Comment by caseymcc** [comment] 2017-06-01 02:28
I think that would be a nice end goal (and if I remember correctly Ruslan mentioned this in the cmake forums), but I don't think you would get the cmake guys to sign up for it just yet. I am sure if you looked around there are a few package handlers (not to mention the OS package managers) so trying to get cmake to favor one over another is going to take a bit of time. If hunter was the de-facto standard for cmake packages I think you could garner support in that direction, but for now I think you have to build that support.

Past that I think you will end up with hunter-ized projects in general. Most of the projects I have seen that use cmake don't use it in the modern fashion with support for the config/versioning system. So that has to be added somewhere. You hope that it goes upstream as some point but you are going to hit resistance with various projects. Past that there are many projects that don't even use cmake so supporting them ends up affecting their code base more than I think some project admins would care for.

Currently if the project uses cmake in a way hunter is expecting (and doesn't have other dependencies) then no hunter-ization is required for it to work. Even for projects that require hunter-ization, if the hunter-ization were move upstream then a secondary repo would not required.

Finally, the way hunter is currently structured it doesn't require cmake modification. Everything works in the cmake realm (granted a lot of round abouts) but it works.

**Comment by ruslo** [comment] 2017-06-01 11:21
> Does anyone has ever thought to move hunter stuff into cmake itself?

Never was a goal. Hunter designed to be used through HunterGate module because
Hunter releases comes much often than CMake releases.

> I mean, if we hack cmake to include HunterGate.cmake and call HunterGate before project,

Adding HunterGate to standard CMake modules is not a bad idea - feel free to discuss it with CMake team and let me know if I need to refactor/beautify HunterGate.cmake. I don't see the point of calling it automatically since we have to set URL/SHA1 of used archive anyway. Where we will get it?

> than what is left is to call hunter_add_package just before each find_package (or find_library, in general anything that needs hunter_add_package stuff), isn't it?

Not all the packages is about `find_package`:
* https://docs.hunter.sh/en/latest/overview/anything.html

So we still have to use `hunter_add_package`, if some packages will be downloaded automatically and other have to be set explicitly then it will look inconsistent I think.

Though in some very far future if all packages will be found by `find_package(* CONFIG REQUIRED)` (including CMake modules, sources and resources, etc.) then the best approach here will be allowing to have kind of a hooks in `find_package(Foo CONFIG REQUIRED)`. We are registering hook and in this hook we call `hunter_add_package(Foo)`.

> Most of the projects I have seen that use cmake don't use it in the modern fashion with support for the config/versioning system

Agree, the biggest problem for now is a poorly written CMake code of the packages or that CMake is not used as a build system or supported only unofficially. That's why I've started CGold: http://cgold.readthedocs.io/en/latest/

**Comment by piribes** [comment] 2017-06-01 11:45
> I am sure if you looked around there are a few package handlers (not to mention the OS package managers) so trying to get cmake to favor one over another is going to take a bit of time.

I agree.

> Most of the projects I have seen that use cmake don't use it in the modern fashion with support for the config/versioning system.

I saw. For those projects, you end up in a situation like you didn't use cmake at all. I believe that a package handler needs a way to extract config/version regardless the build system of a project.

I really like the way hunter manages dependencies by using nothing more that cmake itself. There are plenty of solutions out there, but no one seems to work really well (disclaimer: I haven't tried all of them).

One thing is for sure to me: C++ ecosystem needs a tool that helps developers to use any other projects out there without too much effort, and in a generic way that would be suitable to support a large numbers of workflows.
I know, I'm definitely dreaming :)

Anyway, great work!
Is there any project goal list ?

**Comment by ruslo** [comment] 2017-06-01 12:02
> Is there any project goal list ?

Not explicitly, you can take a look at issues with `enhancement` label. My current goal is about documentation, first CGold then Hunter. That's how I spend my free time currently.

**Comment by piribes** [comment] 2017-06-01 16:28
> I don't see the point of calling it automatically since we have to set URL/SHA1 of used archive anyway. Where we will get it?

I'm using C++, as well as hunter, in my free time, and I don't have too much of it. If I have to fork every single project to add hunter stuff, and then commit to support those packages until they will be merged possibly into the project, I would turn into a CMake programmer. I don't blame anyone for this, that's just a fact I noticed.

For this reason, I'm looking for a solution on how to use third part software, especially open source projects, just by declaring my dependencies and launching some command line program.

Apart from that, it should be possible, given my little understanding of the project (and CMake), to call HunterGate() during HunterGate.cmake inclusion, by looking if some cache variables are set (like HUNTER_GATE_URL and HUNTER_GATE_SHA1 for instance), isn't it ?

> Not all the packages is about find_package:

But we still have some options, I hope. Let's suppose we declare all dependencies in a known location (on HUNTER_ROOT or on some.cmake file on project repository itself, for instance). Now, if the project would like to adopt hunter, it should add some.cmake file in which it should declare dependencies by calling hunter_add_package. On the other hand, we could still add (or overwrite) dependencies for those projects, by adding a file in HUNTER_ROOT. Would it make sense?

> if some packages will be downloaded automatically and other have to be set explicitly then it will look inconsistent I think.

Agree.

> Agree, the biggest problem for now is a poorly written CMake code of the packages or that CMake is not used as a build system or supported only unofficially.

Right, but since hunter support other build systems, I expect that they can be treated as well.

**Comment by ruslo** [comment] 2017-06-02 09:08
> If I have to fork every single project to add hunter stuff, and then commit to support those packages until they will be merged possibly into the project, I would turn into a CMake programmer

Believe me if there was a choice to do the same without involving black magic, I will use it. Few related notes:
* On practice you have to patch projects anyway because of the poorly written CMake code.
* Patches are trivial, it's just HunterGate call, HunterGate module itself and hunter_add_package calls. Meaning that they will not conflict on updates and easy removable.
* We need patches only if project has dependencies.
* Patching done by one developer and reused by unlimited number of developers just by using new URL/SHA1 of HunterGate

> just by declaring my dependencies and launching some command line program

Because of the nature of C++ I doubt you can do it without violating DRY principle.

Note that with Hunter you can do:

    cmake -H. -B_builds -DCMAKE_TOOLCHAIN_FILE=/.../ios.cmake

then

    cmake -H. -B_builds -DCMAKE_TOOLCHAIN_FILE=/.../android.cmake

In both cases Hunter will pick the flags from toolchain and start different
build for 3rd party packages, then add the location of these packages to
the "regular" CMake code.

With separate command line tool you have to manage everything yourself:

    my-package-manager install dependencies.txt -os=iOS -ios-ver=10.2 -ios-dep-ver=9.0 -arch=arm64+armv7a
    cmake -H. -B_builds -DCMAKE_TOOLCHAIN_FILE=/.../ios.cmake -DCMAKE_PREFIX_PATH=/location/of/installed/libs

Plus DRY while introducing optional packages, see:
* https://docs.hunter.sh/en/latest/overview/automatic.html

>  by looking if some cache variables are set (like HUNTER_GATE_URL and HUNTER_GATE_SHA1 for instance), isn't it ?

Not sure I understand. But from where HUNTER_GATE_URL/HUNTER_GATE_SHA1 originally comes from?

If you want an analogy with other package managers you can see URL/SHA1 as a meta version.

Python style:

    package-a==1.0
    package-b==2.0
    package-c==3.0

Hunter style:

    HunterGate(URL ... SHA1 <sha1-as-a-meta-version>)

    hunter_add_package(package-a) # default version from configs/default.cmake 1.0
    hunter_add_package(package-b) # default version from configs/default.cmake 2.0
    hunter_add_package(package-c) # default version from configs/default.cmake 3.0

> some.cmake file on project repository itself, for instance

How it will help? So we have to patch project anyway but will violate DRY for
optional packages (see above).

> Right, but since hunter support other build systems, I expect that they can be treated as well

They are treated well, it's just a very big problem. Usually I mention Boost in this case. The Boost package was added a long time ago (among the first) and still is not complete. It's very hard to be as powerful as CMake.

**Comment by piribes** [comment] 2017-06-03 12:59
> Not sure I understand. But from where HUNTER_GATE_URL/HUNTER_GATE_SHA1 originally comes from?

Can not pass those variables by using environment or -D modifier to CMake? Like we do with HUNTER_ROOT, isn't it?

> How it will help? So we have to patch project anyway but will violate DRY for
optional packages (see above).

You're right, this would somehow violate DRY principle. But projects that use CMake don't really have a clear list of dependencies in their code. They just use some variables. Developers know that some of them are related to other projects, CMake does not.

Moreover, we still need a way to specify dependencies for projects that use other build system.

I'm not so expert neither of CMake nor of hunter. Anyway, I hope my observations will be useful, one way or another.

**Comment by ruslo** [comment] 2017-06-03 13:17
> Can not pass those variables by using environment or -D modifier to CMake? Like we do with HUNTER_ROOT, isn't it?

SHA1 of archive is a local trait of the package:
* user want to clone the project and start build, there is no need to add extra step for getting URL/SHA1 from somewhere (like visiting documentation/fork of the documentation)
* I want to have the ability of using two (or more) different URL/SHA1 for any purposes

From this point of view SHA1 is like fixed SHA1 of Git submodule, if SHA1 of your locally used submodule is global it will affect reproducibility.

> But projects that use CMake don't really have a clear list of dependencies in their code. They just use some variables. Developers know that some of them are related to other projects, CMake does not.

I don't see any problem here. Hunter works fine with this approach:
```cmake
if(FOO_USE_OPENSSL)
  hunter_add_package(OpenSSL)
  find_package(OpenSSL ...)
endif()
```

> Moreover, we still need a way to specify dependencies for projects that use other build system

This is a job for build scheme. As an example: https://github.com/ruslo/hunter/blob/a4e16e4386b03ef0d5ba15487a786b0c6b1a721e/cmake/schemes/url_sha1_autotools.cmake.in#L20-L22

> I'm not so expert neither of CMake nor of hunter. Anyway, I hope my observations will be useful, one way or another.

The questions may be valid but I don't see how any of this can be improved. A lot of features exist and work like it work now for the reason.

**Comment by ruslo** [comment] 2017-06-14 10:43
Hope the answers help, closing.

**Closed by ruslo** 2017-06-14 10:43 UTC
Labels: discussion
