### ISSUE TITLE
Android: unsupported -no-canonical-prefixes

### ISSUE THREAD

**Issue by xsacha** [ruslo/hunter#756] opened 2017-04-07 08:32 UTC
For some reason when building OpenSSL 1.1.0, it complains about this option (-no-canonical-prefixes) being defined. It doesn't seem related to OpenSSL specifically but rather this package hits the issue first.

I was wondering if anyone can figure out why this seems to only happen with Hunter (+ Polly?).

I realise right now this version of OpenSSL is simply disabled for Android but unfortunately android clang has other issues on 1.0.2 so I would like to get this fixed. Since it looks like a Hunter (or maybe Polly) issue, I am sticking it here.

The travis compile is seen here: https://travis-ci.org/ingenue/hunter/jobs/215460184

**Comment by ruslo** [comment] 2017-04-10 13:25
> I was wondering if anyone can figure out why this seems to only happen with Hunter (+ Polly?).

I think this is an OpenSSL issue. The fact that it appears only for Hunter + Polly is because of the exact combination of flags. 

Try to run config manually with these flags:
```
> MACHINE=armv7-a CC=/home/travis/build/ingenue/hunter/_ci/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc RELEASE=2.6.37 SYSTEM=android ARCH=arm ./config "-march=armv7-a -marm -mfpu=neon -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -fexceptions --sysroot=/home/travis/build/ingenue/hunter/_ci/android-ndk-r10e/platforms/android-19/arch-arm -fPIC" threads no-shared
```

What will happen?

**Comment by xsacha** [comment] 2017-05-18 03:04
@ruslo 
When running it manually like above, I get this:
Operating system: aarch64-whatever-android
Configuring for android
Configuring OpenSSL version 1.1.0e (0x1010005fL)
***** Unsupported options: no-canonical-prefixes

**Comment by ruslo** [comment] 2017-05-18 05:31
> When running it manually like above, I get this

It's OpenSSL error as far as I understand. Since you can reproduce it without Hunter you should report the problem upstream, it should be fixed in OpenSSL itself.

**Closed** 2017-06-06 08:40 UTC
Labels: broken package
