### ISSUE TITLE
find_package overload

### ISSUE THREAD

**Issue by regnirpsj** [ruslo/hunter#381] opened 2016-04-09 23:17 UTC
would it be possible to *overload* `find_package` to incorporate package hunting. i was thinking that, with hunter, any `find_package` will essentially become
```
find_package(Foo)
if(NOT Foo_FOUND)
  hunter_add_package(Foo)
  find_package(Foo)
endif()
```
but more sophisticated argument/error handling might necessary.

a similar argument can be also made for `pkg_check_modules`.

**Comment by headupinclouds** [comment] 2016-04-10 01:07
Are you proposing a sort of lazy evaluation package management scheme?  I think the main problem with non-hunter/system `find_package()` calls is the potential for dependency conflicts (version, ABI, etc.).  There is some related discussion here:

https://github.com/ruslo/hunter/issues/203#issuecomment-121503937
https://github.com/ruslo/hunter/issues/10

**Comment by ruslo** [comment] 2016-04-10 01:21
> to overload find_package to incorporate package hunting

So just to clarify you mean add some code so effectively it's possible to write:

```cmake
find_package(Foo)
```

instead of:
```cmake
hunter_add_package(Foo)
find_package(Foo)
```

If so then I was thinking about it at the very beginning and decide to add explicit function. The pros of overloading is that you don't need to patch original packages. Some cases when this became tricky:
* Not all packages use `find_package(Foo)`, `FindFoo.cmake` can be load explicitly by `include`. E.g. OpenCV use [include(FindTIFF)](https://github.com/Itseez/opencv/blob/06ea0aa02b52d1c9ccb5ca392826e0e0c4eb6bd0/cmake/OpenCVFindLibsGrfmt.cmake#L34) instead of `find_package(TIFF)` -> need to patch
* Version control like `find_package(Boost 1.56)` will do not what user expect. When user see overloaded `find_package(Boost 1.56)` he may think that `1.56` is a version from Hunter, but it will be not true: Hunter set version once in `HunterGate` command while loading user's `config.cmake` or global one. Not allowing to do that is a different topic for discussion.
* Not all packages found by `find_package(Foo)`, e.g. `find_executable` may be used too.
* Some projects may overload `find_package` too, this will lead to the conflicts

> Are you proposing a sort of lazy evaluation package management scheme?

+ see this wiki page: https://github.com/ruslo/hunter/wiki/usr.adding.new.package.with.dependencies

**Comment by regnirpsj** [comment] 2016-04-10 10:55
i agree to all that was said above.

i was thinking to use `hunter` in case something is missing. usually, i stick with system installed packages, which seems to work well on fedora. however, windows and containerized ci environments are a bit different. i would like to use `hunter` only if the system doesn't provide what i'm looking for. that's why i think the sequence could be something like:
```
find_package(Foo)
if(NOT Foo_FOUND)
  hunter_add_package(Foo)
  find_package(Foo)
endif()
```
maybe it doesn't have to be an actual *overload* of `find_package` but could be called `hunter_find_package`? also, it might allow for incorporating `pkgconfig` modules.

**Comment by ruslo** [comment] 2016-04-10 11:55
> i would like to use hunter only if the system doesn't provide what i'm looking for

What is the point of that? If you have this package in Hunter - just use it. If not - it's okay for now to use system (just as a workaround).

> i was thinking to use hunter in case something is missing

This is by design not possible. Hunter manage stuff so it creates reproducible build. I.e. it doesn't use the fact that package present in system or not. If one user have `Foo` installed and other haven't, the result of running Hunter should be the same. This is critical for sharing cache binaries. At least the only way to make something close to what you want is to explicitly said that "I want to use this package from system". This should affect **all** packages in current root. Also I don't see the way of sharing such cache (for one user package found in `/usr/lib` for other in `/usr/local/lib` - conflict for binaries) and how it will behave when you update 3rd party by system package manager.

> i stick with system installed packages, which seems to work well on fedora. however, windows and containerized ci environments are a bit different

You can enable Hunter for one system and disable for another. This can be done by [HUNTER_ENABLED](https://github.com/ruslo/hunter/wiki/usr.variables#hunter_enabled) option.

**Comment by ruslo** [comment] 2016-07-14 14:23
Hope this helps, closing.

**Closed by ruslo** 2016-07-14 14:23 UTC
Labels: discussion
