### ISSUE TITLE
add Vulkan Memory Allocator library

### ISSUE THREAD

**Issue by jhs67** [ruslo/hunter#1507] opened 2018-07-30 19:25 UTC
* I'm interested in package `Vulkan Memory Allocator`
* Here is official site of package https://gpuopen.com/gaming-product/vulkan-memory-allocator/

* Official GitHub repository: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator

* Used build system: none, really - single header library

* no dependencies.

This library is a single header release like [catch](https://docs.hunter.sh/en/latest/packages/pkg/Catch.html), but unlike catch it doesn't include it's own cmake file. The single header is in the release tarball, but I am not sure how to setup the hunter config in this case. If you can give me some pointers or direct me to something similar I'll try to create a pull request.

**Comment by ruslo** [comment] 2018-07-30 19:37
> but unlike catch it doesn't include it's own cmake file

Adding CMake code for header-only library is pretty simple effort. Since you've already mentioned `Catch` you can take a look at CMakeLists.txt there. Also you can take this part as boilerplate:
* https://github.com/ruslo/leathers/blob/0cc869358faab455170c3aed93affb075a32cf40/CMakeLists.txt#L89-L139

If you want I can create a hunter-packages fork for temporary version and review, or you can just send pull request upstream and wait for it to be merged.

**Comment by jhs67** [comment] 2018-07-30 20:38
I was hoping there was a way to do it without a fork. I'm not sure how eager upstream would be to merge in the changes - seems like they're focused on the single header approach. Maybe I underestimate.

Either way, if the best route is just to add the cmake file to the release, then please create the fork and I'll look at adding the cmake file. They have an official 2.0.0 release you can use as a base. Thanks.

**Comment by ruslo** [comment] 2018-07-30 20:42
> please create the fork and I'll look at adding the cmake file. They have an official 2.0.0 release you can use as a base

Done: https://github.com/hunter-packages/VulkanMemoryAllocator

**Comment by jhs67** [comment] 2018-07-31 01:01
Getting this hooked up is pretty straight forward. I hit a snag when integrating it with hunter. I wrote an example "boo.cpp" file as per the package adding procedure. This file includes the single header installed by this package. This is all good, but the header depends on the vulkan headers. These are usually system headers, much like OpenGL. Cmake 3.7 even has built in support for find_package(Vulkan).

The problem is none of the build configs (except android) actually have the vulkan headers installed, so they fail. I can just mass comment out the builds and move forward. But on the ubuntu builds, probably all that is needed is an `apt-get install libvulkan-dev` . On osx and windows, the procedure is to download the sdk and set up some environment variables.

I don't know how to do this, so if you think it is worth it, please let me know where I might begin. Otherwise I'll just comment out most of the builds.

**Comment by ruslo** [comment] 2018-07-31 04:55
> but the header depends on the vulkan headers

So this one is not actually true:

> Used build system: none, really - single header library
> no dependencies.

because we do have dependency.

> But on the ubuntu builds, probably all that is needed is an apt-get install libvulkan-dev . On osx and windows, the procedure is to download the sdk and set up some environment variables.

I don't know details about vulkan package but in general solution is to add dependency to Hunter and use `hunter_add_package(vulkan)` in CMake code. As a temporary solution you can use `apt-get` and other approaches, mention it in documentation.

> Otherwise I'll just comment out most of the builds

You mean C++ part? Do not do `#include`? Ok.

**Comment by jhs67** [comment] 2018-07-31 14:32
> You mean C++ part? Do not do #include? Ok.

I mean comment out the travis and appveyor builds.

> add dependency to Hunter and use hunter_add_package(vulkan)

I was just proposing modifing the tests, not hunter itself. It might be possible to include the Vulkan SDK in hunter, but it is a aggregation of a number of projects so setting up a cmake build is too much work for me.

> temporary solution you can use apt-get

I missed this part of the docs - can you point me to it.

**Comment by ruslo** [comment] 2018-07-31 14:46
> I mean comment out the travis and appveyor builds.

Assuming that it's a header only package then Travis/AppVeyor jobs can test `hunter_add_package`, `find_package(... CONFIG REQUIRED)` and `target_link_libraries(...)` part. Just use `int main() {}` as a C++ source code, without any `#include`.

> I missed this part of the docs - can you point me to it.

**You** can mention it in documentation of VulkanMemoryAllocator package, so other users will know about workaround.

**Comment by jhs67** [comment] 2018-07-31 14:53
Ok thanks.

**Comment by jhs67** [comment] 2018-07-31 15:37
I'm getting build errors on the vs-15-2017-win64-cxx17 and vs-14-2015-sdk-8-1 builds:

```
-- [polly] Used toolchain: Visual Studio 14 2015 | SDK 8.1
  -- The C compiler identification is unknown
  -- The CXX compiler identification is unknown
  CMake Error at CMakeLists.txt:5 (project):
    No CMAKE_C_COMPILER could be found.
  CMake Error at CMakeLists.txt:5 (project):
    No CMAKE_CXX_COMPILER could be found.
````

see [here](https://ci.appveyor.com/project/jhs67/hunter-vfmrx/build/job/esiv05lvnmv9pbho) and [here](https://ci.appveyor.com/project/jhs67/hunter-vfmrx/build/job/3wkh3bk3id7gab5s).

**Comment by ruslo** [comment] 2018-07-31 16:02
I think you was building wrong archive.

**Comment by jhs67** [comment] 2018-07-31 16:10
I don't understand. This was a build of the code before you did the hunter-packages release of VulkanMemoryAllocator, but it was the same tree. If that is not what you mean, please explain. Anyway, I've got a build from the hunter-packages release and I'm seeing the same issue [here](https://ci.appveyor.com/project/jhs67/hunter-vfmrx/build/job/2bg0lq8i8v20gc3o) and [here](https://ci.appveyor.com/project/jhs67/hunter-vfmrx/build/job/ru5el2capiirn6ka).

**Comment by ruslo** [comment] 2018-07-31 16:29
I think the problem is about path too long error, try to add `HUNTER_BINARY_DIR` to all entries, e.g.:
* https://github.com/ingenue/hunter/blob/ff832d0b48bab72e0cd661a9d4b7b9c8cff9a5d1/appveyor.yml#L36-L38

**Comment by jhs67** [comment] 2018-07-31 16:44
That seems to be it. Should be straight forward now. Thanks for all the help.

**Comment by ruslo** [comment] 2018-07-31 18:49
Fixed https://github.com/ruslo/hunter/pull/1509

**Closed by ruslo** 2018-07-31 18:49 UTC
Labels: new package
