### ISSUE TITLE
OpenBLAS error under Visual Studio 2015

### ISSUE THREAD

**Issue by seanwarren** [ruslo/hunter#605] opened 2016-12-06 04:52 UTC
When attempting to include OpenBLAS with hunter on the following platform:

- Hunter releases v0.16.36 or v0.16.4
- CMake 3.7.0
- Visual Studio 2015 x64
- Windows 7 SP3

I get this error:
~~~~
[hunter] Calculating Config-SHA1
[hunter] Calculating Toolchain-SHA1
[hunter] HUNTER_ROOT: C:/.hunter
[hunter] [ Hunter-ID: a47baf7 | Config-ID: 7b72d8c | Toolchain-ID: 4ff54d2 ]
[hunter] OPENBLAS_ROOT: C:/.hunter/_Base/a47baf7/7b72d8c/4ff54d2/Install (ver.: 0.2.19-p0)
[hunter] Building OpenBLAS
loading initial cache file C:/.hunter/_Base/a47baf7/7b72d8c/4ff54d2/cache.cmake
loading initial cache file C:/.hunter/_Base/a47baf7/7b72d8c/4ff54d2/Build/OpenBLAS/args.cmake
-- The C compiler identification is MSVC 19.0.24210.0

-- The CXX compiler identification is MSVC 19.0.24210.0

-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe

-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works

-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe

-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works

-- Detecting CXX compile features

-- Detecting CXX compile features - done



[hunter ** INTERNAL **] Expected wiki
[hunter ** INTERNAL **] [Directory:C:/.hunter/_Base/a47baf7/7b72d8c/4ff54d2/Build/OpenBLAS]


------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal

-------------------------------------------------------------------


CMake Error at C:/.hunter/_Base/Download/Hunter/0.16.36/a47baf7/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.16.36/a47baf7/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.16.36/a47baf7/Unpacked/cmake/modules/hunter_fatal_error.cmake:12 (hunter_internal_error)
  CMakeLists.txt:19 (hunter_fatal_error)




-- Configuring incomplete, errors occurred!
See also "C:/.hunter/_Base/a47baf7/7b72d8c/4ff54d2/Build/OpenBLAS/Build/CMakeFiles/CMakeOutput.log".


[hunter ** FATAL ERROR **] Configure step failed (dir: C:/.hunter/_Base/a47baf7/7b72d8c/4ff54d2/Build/OpenBLAS)
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.16.36/a47baf7/Unpacked/cmake/projects/OpenBLAS]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.16.36/a47baf7/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.16.36/a47baf7/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.16.36/a47baf7/Unpacked/cmake/modules/hunter_download.cmake:495 (hunter_fatal_error)
  C:/.hunter/_Base/Download/Hunter/0.16.36/a47baf7/Unpacked/cmake/projects/OpenBLAS/hunter.cmake:26 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.16.36/a47baf7/Unpacked/cmake/modules/hunter_add_package.cmake:87 (include)
  CMakeLists.txt:12 (hunter_add_package)


Configuring incomplete, errors occurred!
~~~~

The following is the most recent entry in  `CMakeOutput.log`:
~~~~
Detecting CXX [] compiler features compiled with the following output:
Change Dir: C:/.hunter/_Base/a47baf7/7b72d8c/4ff54d2/Build/OpenBLAS/Build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_b0c99.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.



Build started 6/12/2016 3:45:01 PM.

Project "C:\.hunter\_Base\a47baf7\7b72d8c\4ff54d2\Build\OpenBLAS\Build\CMakeFiles\CMakeTmp\cmTC_b0c99.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_b0c99.dir\Debug\".

  Creating directory "C:\.hunter\_Base\a47baf7\7b72d8c\4ff54d2\Build\OpenBLAS\Build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_b0c99.dir\Debug\cmTC_b0c99.tlog\".

InitializeBuildStatus:

  Creating "cmTC_b0c99.dir\Debug\cmTC_b0c99.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_b0c99.dir\Debug\\" /Fd"cmTC_b0c99.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue C:\.hunter\_Base\a47baf7\7b72d8c\4ff54d2\Build\OpenBLAS\Build\CMakeFiles\feature_tests.cxx

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24210 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_b0c99.dir\Debug\\" /Fd"cmTC_b0c99.dir\Debug\vc140.pdb" /Gd /TP /errorReport:queue C:\.hunter\_Base\a47baf7\7b72d8c\4ff54d2\Build\OpenBLAS\Build\CMakeFiles\feature_tests.cxx

  

  feature_tests.cxx

Link:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\.hunter\_Base\a47baf7\7b72d8c\4ff54d2\Build\OpenBLAS\Build\CMakeFiles\CMakeTmp\Debug\cmTC_b0c99.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/.hunter/_Base/a47baf7/7b72d8c/4ff54d2/Build/OpenBLAS/Build/CMakeFiles/CMakeTmp/Debug/cmTC_b0c99.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/.hunter/_Base/a47baf7/7b72d8c/4ff54d2/Build/OpenBLAS/Build/CMakeFiles/CMakeTmp/Debug/cmTC_b0c99.lib" /MACHINE:X64  /machine:x64 cmTC_b0c99.dir\Debug\feature_tests.obj

  cmTC_b0c99.vcxproj -> C:\.hunter\_Base\a47baf7\7b72d8c\4ff54d2\Build\OpenBLAS\Build\CMakeFiles\CMakeTmp\Debug\cmTC_b0c99.exe

FinalizeBuildStatus:

  Deleting file "cmTC_b0c99.dir\Debug\cmTC_b0c99.tlog\unsuccessfulbuild".

  Touching "cmTC_b0c99.dir\Debug\cmTC_b0c99.tlog\cmTC_b0c99.lastbuildstate".

Done Building Project "C:\.hunter\_Base\a47baf7\7b72d8c\4ff54d2\Build\OpenBLAS\Build\CMakeFiles\CMakeTmp\cmTC_b0c99.vcxproj" (default targets).



Build succeeded.

    0 Warning(s)

    0 Error(s)



Time Elapsed 00:00:00.63



    Feature record: CXX_FEATURE:0cxx_aggregate_default_initializers
    Feature record: CXX_FEATURE:1cxx_alias_templates
    Feature record: CXX_FEATURE:1cxx_alignas
    Feature record: CXX_FEATURE:1cxx_alignof
    Feature record: CXX_FEATURE:1cxx_attributes
    Feature record: CXX_FEATURE:1cxx_attribute_deprecated
    Feature record: CXX_FEATURE:1cxx_auto_type
    Feature record: CXX_FEATURE:1cxx_binary_literals
    Feature record: CXX_FEATURE:1cxx_constexpr
    Feature record: CXX_FEATURE:1cxx_contextual_conversions
    Feature record: CXX_FEATURE:1cxx_decltype
    Feature record: CXX_FEATURE:1cxx_decltype_auto
    Feature record: CXX_FEATURE:1cxx_default_function_template_args
    Feature record: CXX_FEATURE:1cxx_defaulted_functions
    Feature record: CXX_FEATURE:1cxx_defaulted_move_initializers
    Feature record: CXX_FEATURE:1cxx_delegating_constructors
    Feature record: CXX_FEATURE:1cxx_deleted_functions
    Feature record: CXX_FEATURE:1cxx_digit_separators
    Feature record: CXX_FEATURE:1cxx_enum_forward_declarations
    Feature record: CXX_FEATURE:1cxx_explicit_conversions
    Feature record: CXX_FEATURE:1cxx_extended_friend_declarations
    Feature record: CXX_FEATURE:1cxx_extern_templates
    Feature record: CXX_FEATURE:1cxx_final
    Feature record: CXX_FEATURE:1cxx_func_identifier
    Feature record: CXX_FEATURE:1cxx_generalized_initializers
    Feature record: CXX_FEATURE:1cxx_generic_lambdas
    Feature record: CXX_FEATURE:1cxx_inheriting_constructors
    Feature record: CXX_FEATURE:1cxx_inline_namespaces
    Feature record: CXX_FEATURE:1cxx_lambdas
    Feature record: CXX_FEATURE:1cxx_lambda_init_captures
    Feature record: CXX_FEATURE:1cxx_local_type_template_args
    Feature record: CXX_FEATURE:1cxx_long_long_type
    Feature record: CXX_FEATURE:1cxx_noexcept
    Feature record: CXX_FEATURE:1cxx_nonstatic_member_init
    Feature record: CXX_FEATURE:1cxx_nullptr
    Feature record: CXX_FEATURE:1cxx_override
    Feature record: CXX_FEATURE:1cxx_range_for
    Feature record: CXX_FEATURE:1cxx_raw_string_literals
    Feature record: CXX_FEATURE:1cxx_reference_qualified_functions
    Feature record: CXX_FEATURE:1cxx_return_type_deduction
    Feature record: CXX_FEATURE:1cxx_right_angle_brackets
    Feature record: CXX_FEATURE:1cxx_rvalue_references
    Feature record: CXX_FEATURE:1cxx_sizeof_member
    Feature record: CXX_FEATURE:1cxx_static_assert
    Feature record: CXX_FEATURE:1cxx_strong_enums
    Feature record: CXX_FEATURE:1cxx_template_template_parameters
    Feature record: CXX_FEATURE:1cxx_thread_local
    Feature record: CXX_FEATURE:1cxx_trailing_return_types
    Feature record: CXX_FEATURE:1cxx_unicode_literals
    Feature record: CXX_FEATURE:1cxx_uniform_initialization
    Feature record: CXX_FEATURE:1cxx_unrestricted_unions
    Feature record: CXX_FEATURE:1cxx_user_literals
    Feature record: CXX_FEATURE:1cxx_variable_templates
    Feature record: CXX_FEATURE:1cxx_variadic_macros
    Feature record: CXX_FEATURE:1cxx_variadic_templates
~~~~

**Comment by ruslo** [comment] 2016-12-06 06:39
I have fixed internal error, you can try this release:
* https://github.com/ruslo/hunter/releases/tag/v0.17.2

However the root of the problem is that there is no build scheme for OpenBLAS that do support Visual Studio:
* https://github.com/ruslo/hunter/blob/a69f79fcaf5879ca449aa7a43d606349f05a775e/cmake/projects/OpenBLAS/schemes/OpenBLAS.cmake.in#L17-L19

Somebody have to introduce one.

**Comment by seanwarren** [comment] 2016-12-11 21:32
OK thanks for looking into this!

**Comment by ruslo** [comment] 2017-08-26 13:08
Not a Hunter issue, closing.

**Closed by ruslo** 2017-08-26 13:08 UTC
Labels: broken package
