### ISSUE TITLE
boost iostream + zlib errors 

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#417] opened 2016-05-16 02:52 UTC
A few toolchains are failing for me on travis in a small hunter test project using boost iostream + zlib.  I vaguely recall this being fixed before.  In some cases debug variants have the problem while release builds do not.

Here is some travis output using a recent hunter .travis.yml 

https://travis-ci.org/headupinclouds/hunter_sandbox/builds/130479634

I'll see what I can find.
##

**Comment by ruslo** [comment] 2016-05-16 11:59
>  I vaguely recall this being fixed before. In some cases debug variants have the problem while release builds do not

We are not testing this case. Need to add example with `IOSTREAMS_NO_BZIP2=1` arg.

**Comment by ruslo** [comment] 2016-05-16 18:13
Okay I've found the problem. We are reading only release "part" of ZLIB:
* https://github.com/ruslo/hunter/blob/e4b0df727021fec5da45a21a617903d4145d83ab/cmake/modules/hunter_boost_component_b2_args.cmake#L83

I'm not sure Boost is flexible enough to have different libraries for Debug/Release.
@aadityakalsi you have worked with this stuff, what is your experience?

 Though I think it's possible to apply workaround here. Will do.

**Comment by akalsi87** [comment] 2016-05-16 18:39
@ruslo Are you implying that the issue is that a Debug Boost build needs a Debug ZLIB?

I believe we can query whether Boost is being built Debug or Release.

We have to decide whether Boost debug build implies that BZip2 and/or ZLIB are also built the same with build type (here Debug).

**Comment by ruslo** [comment] 2016-05-16 18:57
> @ruslo Are you implying that the issue is that a Debug Boost build needs a Debug ZLIB?

To be accurate the issue is that we need at least something. If `HUNTER_CONFIGURATION_TYPES=Debug` there will be no Release ZLIB library so `get_target_property(zlib_release ZLIB::zlib IMPORTED_LOCATION_RELEASE)` will return `*-NOTFOUND`.

> We have to decide whether Boost debug build implies that BZip2 and/or ZLIB are also built the same with build type (here Debug).

For now we can assume that Boost Debug should be linked with ZLIB Debug, Boost Release should be linked with ZLIB Release. Report error if it's not. In future this can be fine tuned for not the exact much but for compatible variant (i.e. use Release with MinSizeRel, it's not implemented in Hunter even for CMake part now).

**Comment by headupinclouds** [comment] 2016-05-17 02:00
> Okay I've found the problem. We are reading only release "part" of ZLIB:

@ruslo : Thanks for the fix.

**Comment by ruslo** [comment] 2016-05-17 16:20
@headupinclouds Tests passed, fix merged to `develop`: https://github.com/ruslo/hunter/pull/418 will wait for https://github.com/ruslo/hunter/pull/414 test to finish and release new version. Boost 1.61.0 has `compute` library: http://www.boost.org/users/history/version_1_61_0.html

**Comment by ruslo** [comment] 2016-05-18 22:35
Released: https://github.com/ruslo/hunter/releases/tag/v0.14.22

I've made an update, let's see what'll happen:
* https://travis-ci.org/ruslo/hunter_sandbox/builds/131274312

**Comment by ruslo** [comment] 2016-05-18 23:54
> I've made an update, let's see what'll happen

Looks better, but something wrong with Android and only if host is Linux. Will take a look tomorrow.

**Comment by ruslo** [comment] 2016-05-19 21:47
Magic. With the exception of names of hosts and `SHA1` of cache binaries build log for OSX and Linux are identical line to line but ends differently.

Linux fail (Boost can't find ZLIB):
```
Building the Boost C++ Libraries.


    - zlib                     : no
    - symlinks supported       : yes
    - zlib                     : no  (cached)
```

OSX pass (Boost can find ZLIB):

```
Building the Boost C++ Libraries.


    - zlib                     : yes
    - symlinks supported       : yes
    - zlib                     : yes (cached)
```

Boost configuration:
```
-- [hunter *** DEBUG *** ${TIME}] Build options:
-- [hunter *** DEBUG *** ${TIME}]   -a
-- [hunter *** DEBUG *** ${TIME}]   link=static
-- [hunter *** DEBUG *** ${TIME}]   threading=multi
-- [hunter *** DEBUG *** ${TIME}]   variant=debug,release
-- [hunter *** DEBUG *** ${TIME}]   --layout=tagged
-- [hunter *** DEBUG *** ${TIME}]   toolset=gcc-ndk
-- [hunter *** DEBUG *** ${TIME}]   --user-config=/.../Build/Boost/__iostreams/Build/boost.user.jam
-- [hunter *** DEBUG *** ${TIME}]   --with-iostreams
-- [hunter *** DEBUG *** ${TIME}]   -s
-- [hunter *** DEBUG *** ${TIME}]   NO_COMPRESSION=0
-- [hunter *** DEBUG *** ${TIME}]   -s
-- [hunter *** DEBUG *** ${TIME}]   NO_ZLIB=0
-- [hunter *** DEBUG *** ${TIME}]   -s
-- [hunter *** DEBUG *** ${TIME}]   NO_BZIP2=1
-- [hunter *** DEBUG *** ${TIME}]   -s
-- [hunter *** DEBUG *** ${TIME}]   ZLIB_INCLUDE=/.../Install/include
-- [hunter *** DEBUG *** ${TIME}]   -s
-- [hunter *** DEBUG *** ${TIME}]   ZLIB_LIBPATH=/.../Install/lib
-- [hunter *** DEBUG *** ${TIME}]   -s
-- [hunter *** DEBUG *** ${TIME}]   ZLIB_BINARY=zd
-- [hunter *** DEBUG *** ${TIME}]   linkflags= -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,nocopyreloc -fPIE -pie
-- [hunter *** DEBUG *** ${TIME}]   -j
-- [hunter *** DEBUG *** ${TIME}]   4
-- [hunter *** DEBUG *** ${TIME}] ------
-- [hunter *** DEBUG *** ${TIME}] Boost user jam config:
-- [hunter *** DEBUG *** ${TIME}] ------
-- [hunter *** DEBUG *** ${TIME}] using gcc
  : ndk
  : "${ANDROID_NDK_r10e}/toolchains/arm-linux-androideabi-4.9/prebuilt/${HOST_OS}-x86_64/bin/arm-linux-androideabi-g++" -fexceptions -frtti -Wno-psabi --sysroot=${ANDROID_NDK_r10e}/platforms/android-19/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack -std=c++11 -DANDROID -isystem  ${ANDROID_NDK_r10e}/platforms/android-19/arch-arm/usr/include -isystem  ${ANDROID_NDK_r10e}/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem  ${ANDROID_NDK_r10e}/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem  ${ANDROID_NDK_r10e}/sources/cxx-stl/gnu-libstdc++/4.9/include/backward
  : <archiver> "${ANDROID_NDK_r10e}/toolchains/arm-linux-androideabi-4.9/prebuilt/${HOST_OS}-x86_64/bin/arm-linux-androideabi-gcc-ar"
;
```

**Comment by ruslo** [comment] 2016-05-20 09:47
Okay I've found the difference in internal tests (`bin.v2/config.log`) that doesn't show up in default logs). Problem is about adding `-lrt` library on Linux host:

```
"/.../android-ndk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++"
"-fexceptions"
"-frtti"
"-Wno-psabi"
"--sysroot=/.../android-ndk/android-ndk-r10e/platforms/android-19/arch-arm"
"-funwind-tables"
"-finline-limit=64"
"-fsigned-char"
"-no-canonical-prefixes"
"-march=armv7-a"
"-mfloat-abi=softfp"
"-mfpu=neon"
"-fdata-sections"
"-ffunction-sections"
"-Wa,--noexecstack"
"-std=c++11"
"-DANDROID"
"-isystem"
"/.../android-ndk/android-ndk-r10e/platforms/android-19/arch-arm/usr/include"
"-isystem"
"/.../android-ndk/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include"
"-isystem"
"/.../android-ndk/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include"
"-isystem"
"/.../android-ndk/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/backward"
-L"/.../hunter/_Base/xxxxxxx/3bce312/7416caa/Install/lib"
-Wl,-R
-Wl,"/.../hunter/_Base/xxxxxxx/3bce312/7416caa/Install/lib"
-Wl,-rpath-link
-Wl,"/.../hunter/_Base/xxxxxxx/3bce312/7416caa/Install/lib"
-o
"bin.v2/standalone/ac/gcc-ndk/debug/link-static/threading-multi/zd"
-Wl,--start-group
"bin.v2/standalone/ac/gcc-ndk/debug/link-static/threading-multi/main.o"
-Wl,-Bstatic
-lzd <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< testing ZLIB is present with name 'libzd.a'
-Wl,-Bdynamic
-lrt <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< break stuff (c)
-Wl,--end-group
-g
-pthread
-Wl,--fix-cortex-a8
-Wl,--no-undefined
-Wl,--gc-sections
-Wl,-z,noexecstack
-Wl,-z,relro
-Wl,-z,now
-Wl,-z,nocopyreloc
-fPIE
-pie

/.../android-ndk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lrt
```

works fine on OSX:
```
"/.../android-ndk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++"
"-fexceptions"
"-frtti"
"-Wno-psabi"
"--sysroot=/.../android-ndk/android-ndk-r10e/platforms/android-19/arch-arm"
"-funwind-tables"
"-finline-limit=64"
"-fsigned-char"
"-no-canonical-prefixes"
"-march=armv7-a"
"-mfloat-abi=softfp"
"-mfpu=neon"
"-fdata-sections"
"-ffunction-sections"
"-Wa,--noexecstack"
"-std=c++11"
"-DANDROID"
"-isystem"
"/.../android-ndk/android-ndk-r10e/platforms/android-19/arch-arm/usr/include"
"-isystem"
"/.../android-ndk/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include"
"-isystem"
"/.../android-ndk/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include"
"-isystem"
"/.../android-ndk/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/backward"
-L"/.../hunter/_Base/xxxxxxx/3bce312/7416caa/Install/lib"
-Wl,-R
-Wl,"/.../hunter/_Base/xxxxxxx/3bce312/7416caa/Install/lib"
-Wl,-rpath-link
-Wl,"/.../hunter/_Base/xxxxxxx/3bce312/7416caa/Install/lib"
-o
"bin.v2/standalone/ac/gcc-ndk/debug/link-static/threading-multi/zd"
-Wl,--start-group
"bin.v2/standalone/ac/gcc-ndk/debug/link-static/threading-multi/main.o"
-Wl,-Bstatic
-lzd <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< testing ZLIB is present with name 'libzd.a'
-Wl,-Bdynamic
-Wl,--end-group
-g
-Wl,--fix-cortex-a8
-Wl,--no-undefined
-Wl,--gc-sections
-Wl,-z,noexecstack
-Wl,-z,relro
-Wl,-z,now
-Wl,-z,nocopyreloc
-fPIE
-pie
```

Will report error.

@aadityakalsi Do you know any workarounds?

**Comment by ruslo** [comment] 2016-05-20 10:11
> Will report error

https://svn.boost.org/trac/boost/ticket/12217

**Comment by ruslo** [comment] 2016-10-26 15:47
This one actually is a bug because we can start Boost.iostreams + Android build on Linux host and it will not fail (!) Hence it can be saved to cache and reused producing weird link errors even if host is OSX (when binaries reused from server). I've added a "broken package" guards to prevent such scenario: https://github.com/ruslo/hunter/commit/3628c72c0df9e049e034b33602a5ecdb10588ef9

Note that when we build Boost.iostreams + Android on OSX host and upload binaries to server then they can be correctly reused on Linux host. This is a workaround for this issue.

**Comment by ruslo** [comment] 2017-08-26 13:05
Not a Hunter issue, closing.

**Closed by ruslo** 2017-08-26 13:05 UTC
Labels: broken package
